export const prompts = {
    "analyzingDatasets": [
      { "val": "Describe the data", "prompt": "Can you describe the data?" },
      { "val": "Explain this dataset in one paragraph", "prompt": "Can you explain this dataset in one paragraph?" },
      { "val": "Explain this dataset in simple terms", "prompt": "Can you explain this dataset in simple terms?" },
      { "val": "Explain this dataset like I'm 5 years old", "prompt": "Can you explain this dataset like I'm 5 years old?" },
      { "val": "Identify the main takeaway", "prompt": "What’s the main takeaway from this dataset?" },
      { "val": "Describe the rows and columns", "prompt": "What are the rows and columns in this dataset?" },
      { "val": "Provide insights", "prompt": "What insights do you see here? Give me a numbered list." },
      { "val": "Identify trends", "prompt": "What are the trends shown in this data?" },
      { "val": "Top 10 points", "prompt": "Can you list the top 10 key points?" },
      { "val": "Quick recap", "prompt": "Can you write a one sentence recap of this data?" },      
      { "val": "Key Lessons", "prompt": "What is the key lesson from this dataset?" }
    ],
    "modifyData": [
      { "val": "Clean Data", "prompt": "Can you clean this dataset?" },
      { "val": "Segment Data", "prompt": "Can you segment this data and create a table?" },
    ],
    "uniqueActions": [
      { "val": "Turn into Article", "prompt": "Can you write me an article based on this dataset?" },
      { "val": "Create a presentation", "prompt": "Can you create a presentation based on this dataset?" },
    ],
    "analyzingFinancialData": [
      { "val": "Load and preview the data", "prompt": "Can you load and preview the data?" },
      { "val": "Describe the data", "prompt": "Can you describe the data?" },
      { "val": "Plot the closing price", "prompt": "Can you plot the closing price?" },
      { "val": "Find the date with the highest closing price", "prompt": "What's the date with the highest closing price?" },
      { "val": "Calculate the percentage change", "prompt": "Can you calculate the daily percentage change?" },
      { "val": "Calculate moving averages", "prompt": "Can you calculate a 7-day moving average?" },
      { "val": "Create a candlestick chart", "prompt": "Can you create a candlestick chart?" },
      { "val": "Find the largest single day gain and loss", "prompt": "What's the largest single day gain and loss?" },
      { "val": "Analyze volume", "prompt": "Can you analyze the volume?" },
      { "val": "Check for seasonality", "prompt": "Can you check for seasonality?" },
      { "val": "Compare price with volume", "prompt": "Can you compare the closing price with volume?" },
      { "val": "Calculate volatility", "prompt": "Can you calculate the price volatility?" },
      { "val": "Decompose the time series", "prompt": "Can you decompose the closing price time series?" },
      { "val": "Test for stationarity", "prompt": "Can you test for stationarity using the Augmented Dickey-Fuller test?" },
      { "val": "Autocorrelation and partial autocorrelation plots", "prompt": "Can you show the autocorrelation and partial autocorrelation plots?" },
      { "val": "Implement a time series model", "prompt": "Can you implement an ARIMA model to predict future prices?" },
      { "val": "Plot Bollinger Bands", "prompt": "Can you plot Bollinger Bands?" },
      { "val": "Find important dates", "prompt": "Can you identify dates of significant changes in volume or price?" },
      { "val": "Plot a histogram of the daily returns", "prompt": "Can you plot a histogram of daily returns?" },
      { "val": "Rolling window operations", "prompt": "Can you perform a rolling sum over a 7-day window?" },
      { "val": "Price Increase", "prompt": "What's the duration of the fastest price increase from low to high?" },
      { "val": "Price Decrease", "prompt": "What's the duration of the fastest price decrease from high to low?" }
    ],
    "visualizations": [
      { "val": "Create a graph", "prompt": "Can you create a graph using this data?" },
      { "val": "Create a chart", "prompt": "Can you create a chart using this data?" },
      { "val": "Create a heatmap", "prompt": "Can you create a heatmap using this data?" },
      { "val": "Create 10 visuals", "prompt": "Can you create 10 visuals to represent different data?" },
      { "val": "Word Cloud", "prompt": "Can you create a visual word cloud?" },
      { "val": "Visual Chart", "prompt": "Create a visual chart, based on this data." },
      { "val": "Trends in a visual format", "prompt": "Show me the top trends in a visual format" },
    ]
  }