/**
 * Polymarket endpoint config: query, name, description, group, and params.
 * listQuery = call this query first to populate dropdown (value from id, label from title/name + id).
 */
export const POLYMARKET_GROUPS = {
  events: "Events",
  markets: "Markets",
  prices: "Prices",
  trades: "Trades",
  liveDataWebsocket: "Live data - WebSocket",
};

/** Trade response fields from https://docs.polymarket.com/api-reference/core/get-trades-for-a-user-or-markets */
export const TRADES_RESPONSE_FIELDS = [
  "proxyWallet", "side", "asset", "conditionId", "size", "price", "timestamp",
  "title", "slug", "icon", "eventSlug", "outcome", "outcomeIndex", "name",
  "pseudonym", "bio", "profileImage", "profileImageOptimized", "transactionHash",
];

/** Event response fields (List events) — top-level + flattened nested keys from gamma-api.polymarket.com/events */
export const EVENTS_RESPONSE_FIELDS = [
  "id", "ticker", "slug", "title", "subtitle", "description", "resolutionSource",
  "startDate", "creationDate", "endDate", "image", "icon", "active", "closed", "archived", "new", "featured", "restricted",
  "liquidity", "volume", "openInterest", "sortBy", "category", "subcategory", "isTemplate", "templateVariables",
  "published_at", "createdBy", "updatedBy", "createdAt", "updatedAt", "commentsEnabled", "competitive",
  "volume24hr", "volume1wk", "volume1mo", "volume1yr", "featuredImage", "disqusThread", "parentEvent",
  "enableOrderBook", "liquidityAmm", "liquidityClob", "negRisk", "negRiskMarketID", "negRiskFeeBips", "commentCount",
  "imageOptimized_id", "imageOptimized_imageUrlSource", "imageOptimized_imageUrlOptimized", "imageOptimized_imageSizeKbSource",
  "imageOptimized_imageSizeKbOptimized", "imageOptimized_imageOptimizedComplete", "imageOptimized_imageOptimizedLastUpdated",
  "imageOptimized_relID", "imageOptimized_field", "imageOptimized_relname",
  "iconOptimized_id", "iconOptimized_imageUrlSource", "iconOptimized_imageUrlOptimized", "iconOptimized_imageSizeKbSource",
  "iconOptimized_imageSizeKbOptimized", "iconOptimized_imageOptimizedComplete", "iconOptimized_imageOptimizedLastUpdated",
  "iconOptimized_relID", "iconOptimized_field", "iconOptimized_relname",
  "featuredImageOptimized_id", "featuredImageOptimized_imageUrlSource", "featuredImageOptimized_imageUrlOptimized",
  "featuredImageOptimized_imageSizeKbSource", "featuredImageOptimized_imageSizeKbOptimized",
  "featuredImageOptimized_imageOptimizedComplete", "featuredImageOptimized_imageOptimizedLastUpdated",
  "featuredImageOptimized_relID", "featuredImageOptimized_field", "featuredImageOptimized_relname",
  "subEvents", "markets", "series", "categories", "collections", "tags",
  "cyom", "closedTime", "showAllOutcomes", "showMarketImages", "automaticallyResolved", "enableNegRisk", "automaticallyActive",
  "eventDate", "startTime", "eventWeek", "seriesSlug", "score", "elapsed", "period", "live", "ended", "finishedTimestamp",
  "gmpChartMode", "eventCreators", "tweetCount", "chats", "featuredOrder", "estimateValue", "cantEstimate", "estimatedValue",
  "templates", "spreadsMainLine", "totalsMainLine", "carouselMap", "pendingDeployment", "deploying",
  "deployingTimestamp", "scheduledDeploymentTimestamp", "gameStatus",
  "marketId", "eventId", "outcome", "price", "winner",
];

/** Market response fields (List markets) — top-level + flattened nested keys from gamma-api.polymarket.com/markets */
export const MARKETS_RESPONSE_FIELDS = [
  "id", "question", "conditionId", "slug", "twitterCardImage", "resolutionSource", "endDate", "category", "ammType",
  "liquidity", "sponsorName", "sponsorImage", "startDate", "xAxisValue", "yAxisValue", "denominationToken", "fee",
  "image", "icon", "lowerBound", "upperBound", "description", "outcomes", "outcomePrices", "volume", "active",
  "marketType", "formatType", "lowerBoundDate", "upperBoundDate", "closed", "marketMakerAddress", "createdBy", "updatedBy",
  "createdAt", "updatedAt", "closedTime", "wideFormat", "new", "mailchimpTag", "featured", "archived", "resolvedBy",
  "restricted", "marketGroup", "groupItemTitle", "groupItemThreshold", "questionID", "umaEndDate", "enableOrderBook",
  "orderPriceMinTickSize", "orderMinSize", "umaResolutionStatus", "curationOrder", "volumeNum", "liquidityNum",
  "endDateIso", "startDateIso", "umaEndDateIso", "hasReviewedDates", "readyForCron", "commentsEnabled",
  "volume24hr", "volume1wk", "volume1mo", "volume1yr", "gameStartTime", "secondsDelay", "clobTokenIds", "disqusThread",
  "shortOutcomes", "teamAID", "teamBID", "umaBond", "umaReward", "fpmmLive",
  "volume24hrAmm", "volume1wkAmm", "volume1moAmm", "volume1yrAmm", "volume24hrClob", "volume1wkClob", "volume1moClob", "volume1yrClob",
  "volumeAmm", "volumeClob", "liquidityAmm", "liquidityClob", "makerBaseFee", "takerBaseFee", "customLiveness",
  "acceptingOrders", "notificationsEnabled", "score",
  "imageOptimized_id", "imageOptimized_imageUrlSource", "imageOptimized_imageUrlOptimized", "imageOptimized_imageSizeKbSource",
  "imageOptimized_imageSizeKbOptimized", "imageOptimized_imageOptimizedComplete", "imageOptimized_imageOptimizedLastUpdated",
  "imageOptimized_relID", "imageOptimized_field", "imageOptimized_relname",
  "iconOptimized_id", "iconOptimized_imageUrlSource", "iconOptimized_imageUrlOptimized", "iconOptimized_imageSizeKbSource",
  "iconOptimized_imageSizeKbOptimized", "iconOptimized_imageOptimizedComplete", "iconOptimized_imageOptimizedLastUpdated",
  "iconOptimized_relID", "iconOptimized_field", "iconOptimized_relname",
  "events", "categories", "tags", "creator", "ready", "funded", "pastSlugs", "readyTimestamp", "fundedTimestamp",
  "acceptingOrdersTimestamp", "competitive", "rewardsMinSize", "rewardsMaxSpread", "spread", "automaticallyResolved",
  "oneDayPriceChange", "oneHourPriceChange", "oneWeekPriceChange", "oneMonthPriceChange", "oneYearPriceChange",
  "lastTradePrice", "bestBid", "bestAsk", "automaticallyActive", "clearBookOnStart", "chartColor", "seriesColor",
  "showGmpSeries", "showGmpOutcome", "manualActivation", "negRiskOther", "gameId", "groupItemRange", "sportsMarketType",
  "line", "umaResolutionStatuses", "pendingDeployment", "deploying", "deployingTimestamp", "scheduledDeploymentTimestamp",
  "rfqEnabled", "eventStartTime",
  "marketId", "eventId", "outcome", "price", "winner",
];

export const PRICES_HISTORY_RESPONSE_FIELDS = [
  "market",
  "t",
  "p",
];

export const ENDPOINTS = [
  // Events
  {
    query: "listEvents",
    name: "List events",
    description: "Fetch events with optional filters (limit, offset, active, closed, dates, etc.).",
    group: "events",
    responseFields: EVENTS_RESPONSE_FIELDS,
    params: [
      { key: "outcomeOptimizedFormat", label: "Outcome-optimized format", required: false, type: "boolean", default: "", hint: "Flatten outcomes with prices; add winner for closed markets" },
      { key: "limit", label: "Limit", required: false, type: "number", default: 20, hint: "Range >= 0" },
      { key: "offset", label: "Offset", required: false, type: "number", default: 0, hint: "Range >= 0" },
      { key: "order", label: "Order", required: false, type: "text", hint: "Comma-separated fields to order by" },
      { key: "ascending", label: "Ascending", required: false, type: "boolean", default: "" },
      { key: "id", label: "Event ID(s)", required: false, type: "text", hint: "Comma-separated event IDs" },
      { key: "tag_id", label: "Tag ID", required: false, type: "number" },
      { key: "exclude_tag_id", label: "Exclude tag ID(s)", required: false, type: "text", hint: "Comma-separated tag IDs to exclude" },
      { key: "slug", label: "Slug(s)", required: false, type: "text", hint: "Comma-separated event slugs" },
      { key: "tag_slug", label: "Tag slug", required: false, type: "text" },
      { key: "related_tags", label: "Related tags", required: false, type: "boolean", default: "" },
      { key: "active", label: "Active only", required: false, type: "boolean", default: "" },
      { key: "archived", label: "Archived only", required: false, type: "boolean", default: "" },
      { key: "featured", label: "Featured only", required: false, type: "boolean", default: "" },
      { key: "cyom", label: "CYOM", required: false, type: "boolean", default: "" },
      { key: "include_chat", label: "Include chat", required: false, type: "boolean", default: "" },
      { key: "include_template", label: "Include template", required: false, type: "boolean", default: "" },
      { key: "recurrence", label: "Recurrence", required: false, type: "text" },
      { key: "closed", label: "Closed only", required: false, type: "boolean", default: "" },
      { key: "liquidity_min", label: "Liquidity min", required: false, type: "number" },
      { key: "liquidity_max", label: "Liquidity max", required: false, type: "number" },
      { key: "volume_min", label: "Volume min", required: false, type: "number" },
      { key: "volume_max", label: "Volume max", required: false, type: "number" },
      { key: "start_date_min", label: "Start date min", required: false, type: "text", hint: "ISO date-time" },
      { key: "start_date_max", label: "Start date max", required: false, type: "text", hint: "ISO date-time" },
      { key: "end_date_min", label: "End date min", required: false, type: "text", hint: "ISO date-time" },
      { key: "end_date_max", label: "End date max", required: false, type: "text", hint: "ISO date-time" },
    ],
  },
  {
    query: "getEvent",
    name: "Get event by ID",
    description: "Get a single event by ID. Use List events to get IDs, or pull list below.",
    group: "events",
    params: [
      { key: "id", label: "Event ID", required: true, type: "text", listQuery: "listEvents", listLabelKey: "title", listValueKey: "id" },
      { key: "outcomeOptimizedFormat", label: "Outcome-optimized format", required: false, type: "boolean", default: "", hint: "Flatten outcomes with prices; add winner for closed markets" },
    ],
  },
  {
    query: "getEventBySlug",
    name: "Get event by slug",
    description: "Get a single event by URL slug (e.g. from event page URL).",
    group: "events",
    params: [
      { key: "slug", label: "Event slug", required: true, type: "text" },
      { key: "outcomeOptimizedFormat", label: "Outcome-optimized format", required: false, type: "boolean", default: "", hint: "Flatten outcomes with prices; add winner for closed markets" },
    ],
  },
  {
    query: "getEventTags",
    name: "Get event tags",
    description: "Get tags for an event. Requires event ID (from List events or Get event by ID).",
    group: "events",
    params: [
      { key: "id", label: "Event ID", required: true, type: "text", listQuery: "listEvents", listLabelKey: "title", listValueKey: "id" },
    ],
  },
  // Markets
  {
    query: "listMarkets",
    name: "List markets",
    description: "Fetch markets with optional filters. All query params supported.",
    group: "markets",
    responseFields: MARKETS_RESPONSE_FIELDS,
    params: [
      { key: "outcomeOptimizedFormat", label: "Outcome-optimized format", required: false, type: "boolean", default: "", hint: "Flatten outcomes with prices; add winner for closed markets" },
      { key: "limit", label: "Limit", required: false, type: "number", default: 20, hint: "Range >= 0" },
      { key: "offset", label: "Offset", required: false, type: "number", default: 0, hint: "Range >= 0" },
      { key: "order", label: "Order", required: false, type: "text", hint: "Comma-separated fields to order by" },
      { key: "ascending", label: "Ascending", required: false, type: "boolean", default: "" },
      { key: "id", label: "Market ID(s)", required: false, type: "text", hint: "Comma-separated market IDs" },
      { key: "slug", label: "Slug(s)", required: false, type: "text", hint: "Comma-separated market slugs" },
      { key: "clob_token_ids", label: "CLOB token IDs", required: false, type: "text", hint: "Comma-separated" },
      { key: "condition_ids", label: "Condition ID(s)", required: false, type: "text", hint: "Comma-separated condition IDs" },
      { key: "market_maker_address", label: "Market maker address", required: false, type: "text", hint: "Comma-separated addresses" },
      { key: "liquidity_num_min", label: "Liquidity min", required: false, type: "number" },
      { key: "liquidity_num_max", label: "Liquidity max", required: false, type: "number" },
      { key: "volume_num_min", label: "Volume min", required: false, type: "number" },
      { key: "volume_num_max", label: "Volume max", required: false, type: "number" },
      { key: "start_date_min", label: "Start date min", required: false, type: "text", hint: "ISO date-time" },
      { key: "start_date_max", label: "Start date max", required: false, type: "text", hint: "ISO date-time" },
      { key: "end_date_min", label: "End date min", required: false, type: "text", hint: "ISO date-time" },
      { key: "end_date_max", label: "End date max", required: false, type: "text", hint: "ISO date-time" },
      { key: "tag_id", label: "Tag ID", required: false, type: "number" },
      { key: "related_tags", label: "Related tags", required: false, type: "boolean", default: "" },
      { key: "cyom", label: "CYOM", required: false, type: "boolean", default: "" },
      { key: "uma_resolution_status", label: "UMA resolution status", required: false, type: "text" },
      { key: "game_id", label: "Game ID", required: false, type: "text" },
      { key: "sports_market_types", label: "Sports market types", required: false, type: "text", hint: "Comma-separated" },
      { key: "rewards_min_size", label: "Rewards min size", required: false, type: "number" },
      { key: "question_ids", label: "Question ID(s)", required: false, type: "text", hint: "Comma-separated" },
      { key: "include_tag", label: "Include tag", required: false, type: "boolean", default: "" },
      { key: "closed", label: "Closed only", required: false, type: "boolean", default: "" },
    ],
  },
  {
    query: "getMarket",
    name: "Get market by ID",
    description: "Get a single market by ID. Use List markets to get IDs, or pull list below.",
    group: "markets",
    responseFields: MARKETS_RESPONSE_FIELDS,
    params: [
      { key: "id", label: "Market ID", required: true, type: "text", listQuery: "listMarkets", listLabelKey: "question", listValueKey: "id" },
      { key: "outcomeOptimizedFormat", label: "Outcome-optimized format", required: false, type: "boolean", default: "", hint: "Flatten outcomes with prices; add winner for closed markets" },
    ],
  },
  {
    query: "getMarketBySlug",
    name: "Get market by slug",
    description: "Get a single market by URL slug.",
    group: "markets",
    responseFields: MARKETS_RESPONSE_FIELDS,
    params: [
      { key: "slug", label: "Market slug", required: true, type: "text" },
      { key: "outcomeOptimizedFormat", label: "Outcome-optimized format", required: false, type: "boolean", default: "", hint: "Flatten outcomes with prices; add winner for closed markets" },
    ],
  },
  {
    query: "getMarketTags",
    name: "Get market tags by ID",
    description: "Get tags for a market. Requires market ID (from List markets or Get market by ID).",
    group: "markets",
    params: [
      { key: "id", label: "Market ID", required: true, type: "text", listQuery: "listMarkets", listLabelKey: "question", listValueKey: "id" },
    ],
  },
  {
    query: "getTopHolders",
    name: "Get top holders for markets",
    description: "Top holders per market. Requires condition IDs from List markets (conditionId).",
    group: "markets",
    params: [
      { key: "market", label: "Condition ID(s)", required: true, type: "text", hint: "Comma-separated condition IDs from List markets" },
      { key: "limit", label: "Limit per token", required: false, type: "number", default: 20 },
      { key: "minBalance", label: "Min balance", required: false, type: "number", default: 1 },
    ],
  },
  {
    query: "getOpenInterest",
    name: "Get open interest",
    description: "Open interest; optional market condition IDs.",
    group: "markets",
    params: [
      { key: "market", label: "Condition ID(s)", required: false, type: "text", hint: "Comma-separated; omit for all" },
    ],
  },
  {
    query: "getLiveVolume",
    name: "Get live volume for an event",
    description: "Live volume for an event. Requires event ID (from List events).",
    group: "markets",
    params: [
      { key: "id", label: "Event ID", required: true, type: "text", listQuery: "listEvents", listLabelKey: "title", listValueKey: "id" },
    ],
  },
  {
    query: "getPricesHistory",
    name: "Price history",
    description: "Retrieve historical prices for one or more CLOB asset IDs. Select a market to pick Yes/No token IDs, or paste IDs directly.",
    group: "prices",
    responseFields: PRICES_HISTORY_RESPONSE_FIELDS,
    params: [
      {
        key: "market",
        label: "Market (asset ID)",
        required: true,
        type: "text",
        listQuery: "listMarkets",
        listLabelKey: "question",
        listValueKey: "id",
        hint: "Select a market then choose Yes/No token IDs, or enter asset ID(s) directly (comma-separated).",
      },
      { key: "startTs", label: "Start timestamp", required: false, type: "number", hint: "Unix timestamp (seconds)" },
      { key: "endTs", label: "End timestamp", required: false, type: "number", hint: "Unix timestamp (seconds)" },
      {
        key: "interval",
        label: "Interval",
        required: false,
        type: "select",
        options: ["max", "all", "1m", "1w", "1d", "6h", "1h"],
        hint: "Aggregation interval",
      },
      { key: "fidelity", label: "Fidelity (minutes)", required: false, type: "number", hint: "Default: 1" },
    ],
  },
  // Trades (Data API: https://data-api.polymarket.com/api-reference/core/get-trades-for-a-user-or-markets) — under construction
  {
    query: "getTradesByMarket",
    name: "Get trades by market",
    description: "Get trades for one or more markets (condition IDs). Use List markets to pick a market, or enter condition ID(s) comma-separated.",
    group: "trades",
    broken: true,
    responseFields: TRADES_RESPONSE_FIELDS,
    params: [
      { key: "market", label: "Condition ID(s)", required: true, type: "text", listQuery: "listMarkets", listLabelKey: "question", listValueKey: "conditionId", hint: "Comma-separated condition IDs from List markets" },
      { key: "limit", label: "Limit", required: false, type: "number", default: 100 },
      { key: "offset", label: "Offset", required: false, type: "number", default: 0 },
      { key: "side", label: "Side", required: false, type: "text", hint: "BUY or SELL" },
    ],
  },
  // Live data - WebSocket (handled separately in index.js)
  {
    query: "wsPrice",
    name: "Price",
    description: "Live price change stream via WebSocket. Subscribe to market token IDs to receive real-time orderbook price updates.",
    group: "liveDataWebsocket",
    wsType: true,
    params: [
      {
        key: "market_token_id",
        label: "Token / Condition ID",
        required: true,
        type: "text",
        listQuery: "listMarkets",
        listLabelKey: "question",
        listValueKey: "conditionId",
        listFilter: { closed: "false" },
        hint: "Select a market (uses condition_id) or enter token/condition ID(s) comma-separated.",
      },
    ],
  },
  {
    query: "wsLastTradePrice",
    name: "Last trade price",
    description: "Live last trade price stream via WebSocket. Streams executed trade prints (last_trade_price) for subscribed market token IDs.",
    group: "liveDataWebsocket",
    wsType: true,
    params: [
      {
        key: "market_token_id",
        label: "Token / Condition ID",
        required: true,
        type: "text",
        listQuery: "listMarkets",
        listLabelKey: "question",
        listValueKey: "conditionId",
        listFilter: { closed: "false" },
        hint: "Select a market (uses condition_id) or enter token/condition ID(s) comma-separated.",
      },
    ],
  },
  {
    query: "wsOrderbookSnapshot",
    name: "Orderbook snapshot",
    description: "Live orderbook book events via WebSocket (event_type = book). Streams full aggregated orderbook snapshots for subscribed token IDs.",
    group: "liveDataWebsocket",
    wsType: true,
    params: [
      {
        key: "market_token_id",
        label: "Token / Condition ID",
        required: true,
        type: "text",
        listQuery: "listMarkets",
        listLabelKey: "question",
        listValueKey: "conditionId",
        listFilter: { closed: "false" },
        hint: "Select a market (uses condition_id) or enter token/condition ID(s) comma-separated.",
      },
    ],
  },
  {
    query: "wsTickSizeChange",
    name: "Tick size change",
    description: "Live tick_size_change events via WebSocket. Streams tick size updates for subscribed token IDs.",
    group: "liveDataWebsocket",
    wsType: true,
    params: [
      {
        key: "market_token_id",
        label: "Token / Condition ID",
        required: true,
        type: "text",
        listQuery: "listMarkets",
        listLabelKey: "question",
        listValueKey: "conditionId",
        listFilter: { closed: "false" },
        hint: "Select a market (uses condition_id) or enter token/condition ID(s) comma-separated.",
      },
    ],
  },
  {
    query: "wsBestBidAsk",
    name: "Best bid / ask",
    description: "Live best_bid_ask events via WebSocket (requires custom_feature_enabled: true). Streams best bid/ask and spread for subscribed token IDs.",
    group: "liveDataWebsocket",
    wsType: true,
    params: [
      {
        key: "market_token_id",
        label: "Token / Condition ID",
        required: true,
        type: "text",
        listQuery: "listMarkets",
        listLabelKey: "question",
        listValueKey: "conditionId",
        listFilter: { closed: "false" },
        hint: "Select a market (uses condition_id) or enter token/condition ID(s) comma-separated.",
      },
    ],
  },
  {
    query: "wsNewMarket",
    name: "New market",
    description: "Live new_market events via WebSocket (requires custom_feature_enabled: true). Streams new market creation events.",
    group: "liveDataWebsocket",
    wsType: true,
    params: [
      {
        key: "market_token_id",
        label: "Token / Condition ID",
        required: false,
        type: "text",
        hint: "Optional filter: enter token/condition ID(s). Leave blank to stream all.",
      },
    ],
  },
  {
    query: "wsMarketResolved",
    name: "Market resolved",
    description: "Live market_resolved events via WebSocket (requires custom_feature_enabled: true). Streams market resolution events.",
    group: "liveDataWebsocket",
    wsType: true,
    params: [
      {
        key: "market_token_id",
        label: "Token / Condition ID",
        required: false,
        type: "text",
        hint: "Optional filter: enter token/condition ID(s). Leave blank to stream all.",
      },
    ],
  },
  {
    query: "getTradesByUser",
    name: "Get trades by user",
    description: "Get trades for a user (wallet address). Enter a 0x-prefixed Ethereum address.",
    group: "trades",
    broken: true,
    responseFields: TRADES_RESPONSE_FIELDS,
    params: [
      { key: "user", label: "User (wallet address)", required: true, type: "text", hint: "0x-prefixed address (40 hex chars)" },
      { key: "limit", label: "Limit", required: false, type: "number", default: 100 },
      { key: "offset", label: "Offset", required: false, type: "number", default: 0 },
      { key: "side", label: "Side", required: false, type: "text", hint: "BUY or SELL" },
    ],
  },
];
