const getBigData = async () => {
    const amplitude = 1; // Amplitude of the wave
    const frequency = 1; // Frequency of the wave (number of cycles within 2π)
    const phase = 0; // Phase offset
    const numberOfPoints = 1000; // Number of data points

    const data = [];

    for (let i = 0; i < numberOfPoints; i++) {
        const x = ((i / (numberOfPoints - 1)) * 4 - 2) * Math.PI; // Values between -2π and 2π
        const sinX = amplitude * Math.sin(frequency * x + phase);
        const cosX = amplitude * Math.cos(frequency * x + phase);
        let tanX = amplitude * Math.tan(frequency * x + phase);
        let cscX = 1 / sinX;
        let secX = 1 / cosX;
        let cotX = 1 / tanX;

        // Skip values above 4 and below -4
        if (tanX > 4 || tanX < -4) {
        tanX = null;
        }
        if (cscX > 4 || cscX < -4) {
        cscX = null;
        }
        if (secX > 4 || secX < -4) {
        secX = null;
        }
        if (cotX > 4 || cotX < -4) {
        cotX = null;
        }

        data.push({ x, sinX, cosX, tanX, cscX, secX, cotX });
    }

    return data;
}

export async function prepareChartData() {
    const bigData = await getBigData(); // Fetch the data asynchronously

    function formatNumber(value) {
        value /= 1000_000;
        return `${Math.floor(value)}M`;
    }

    const numFormatter = new Intl.NumberFormat("en-US");

    const dateFormatter = new Intl.DateTimeFormat("en-US");

    const tooltip = {
        renderer: ({ title, datum, xKey, yKey }) => ({
          title,
          content: `${dateFormatter.format(datum[xKey])}: ${datum[yKey]}`,
        }),
    };


    const demoCharts = [
        {
            id: 'bar0',
            title: "Simple Bar Chart",
            description: "Bar Series visualises numerical data with proportional bars",
            footnote: "Source: Department for Digital, Culture, Media & Sport",
            data: [
                { year: "2016", visitors: 46636720 },
                { year: "2017", visitors: 48772922 },
                { year: "2018", visitors: 50800193 },
                { year: "2019", visitors: 48023342 },
                { year: "2020", visitors: 47271912 },
                { year: "2021", visitors: 47155093 },
                { year: "2022", visitors: 49441678 },
                { year: "2023", visitors: 50368190 },
              ],
            series: [
                {
                  type: "bar",
                  xKey: "year",
                  yKey: "visitors",
                  label: {
                    formatter: ({ value }) => formatNumber(value),
                  },
                  tooltip: {
                    renderer: ({ datum, xKey, yKey }) => {
                      return { title: datum[xKey], content: formatNumber(datum[yKey]) };
                    },
                  },
                },
              ],            
            axes: [
                {
                    type: "category",
                    position: "bottom",
                    title: {
                    text: "Year",
                    },
                },
                {
                    type: "number",
                    position: "left",
                    title: {
                    text: "Total Visitors",
                    },
                    label: {
                    formatter: ({ value }) => formatNumber(value),
                    },
                    crosshair: {
                    label: {
                        renderer: ({ value }) =>
                        `<div style="padding: 0 7px; border-radius: 2px; line-height: 1.7em; background-color: rgb(71,71,71); color: rgb(255, 255, 255);">${formatNumber(value)}</div>`,
                    },
                    },
                },
            ],
        },
        {
            id: 'bar1',
            title: "Group Stacked Bar",
            description: "Bar Charts can be grouped or stacked",
            footnote: null,
            data: [
                {
                  dolphin: "Peter",
                  interactionDurationTM: 1.23,
                  interactionDurationTMLower: 0.8,
                  interactionDurationTMUpper: 1.44,
                  interactionDurationYM: 2.85,
                  interactionDurationYMLower: 2.22,
                  interactionDurationYMUpper: 3.61,
                  numberOfLooksTM: 60,
                  numberOfLooksYM: 64,
                },
                {
                  dolphin: "Mary",
                  interactionDurationTM: 1.35,
                  interactionDurationTMLower: 0.9,
                  interactionDurationTMUpper: 1.59,
                  interactionDurationYM: 2.59,
                  interactionDurationYMLower: 2.09,
                  interactionDurationYMUpper: 2.85,
                  numberOfLooksTM: 57,
                  numberOfLooksYM: 93,
                },
                {
                  dolphin: "Mercutio",
                  interactionDurationTM: 1.4,
                  interactionDurationTMLower: 1.32,
                  interactionDurationTMUpper: 1.46,
                  interactionDurationYM: 1.45,
                  interactionDurationYMLower: 1.1,
                  interactionDurationYMUpper: 1.54,
                  numberOfLooksTM: 238,
                  numberOfLooksYM: 217,
                },
                {
                  dolphin: "Ada",
                  interactionDurationTM: 1.1,
                  interactionDurationTMLower: 0.89,
                  interactionDurationTMUpper: 1.45,
                  interactionDurationYM: 1.47,
                  interactionDurationYMLower: 1.35,
                  interactionDurationYMUpper: 1.64,
                  numberOfLooksTM: 237,
                  numberOfLooksYM: 217,
                },
            ],
            series: [
            {
                type: "bar",
                xKey: "dolphin",
                yKey: "interactionDurationTM",
                yName: "Interaction Duration - Transparent Mirror",
                legendItemName: "Interaction Duration - Transparent Mirror",
                stackGroup: "ID",
                errorBar: {
                yLowerKey: "interactionDurationTMLower",
                yUpperKey: "interactionDurationTMUpper",
                },
            },
            {
                type: "bar",
                xKey: "dolphin",
                yKey: "interactionDurationYM",
                yName: "Interaction Duration - Yellow Mirror",
                legendItemName: "Interaction Duration - Yellow Mirror",
                stackGroup: "ID",
                errorBar: {
                yLowerKey: "interactionDurationYMLower",
                yUpperKey: "interactionDurationYMUpper",
                },
            },
            {
                type: "bar",
                xKey: "dolphin",
                yKey: "numberOfLooksTM",
                yName: "Number of Looks - Transparent Mirror",
                legendItemName: "Number of Looks - Transparent Mirror",
                stackGroup: "NOL",
            },
            {
                type: "bar",
                xKey: "dolphin",
                yKey: "numberOfLooksYM",
                yName: "Number of Looks - Yellow Mirror",
                legendItemName: "Number of Looks - Yellow Mirror",
                stackGroup: "NOL",
            },
            ],
            axes: [
            {
                position: "top",
                type: "category",
                keys: ["dolphin"],
                title: {
                text: "Dolphin",
                },
                paddingInner: 0.5,
                paddingOuter: 0.2,
                crossLines: [
                {
                    type: "range",
                    range: ["Peter", "Peter"],
                    strokeWidth: 0,
                },
                {
                    type: "range",
                    range: ["Mercutio", "Mercutio"],
                    strokeWidth: 0,
                },
                ],
            },
            {
                position: "left",
                type: "number",
                keys: ["interactionDurationTM", "interactionDurationYM"],
                title: {
                text: "Duration of Interaction (seconds)",
                },
            },
            {
                position: "right",
                type: "number",
                title: {
                text: "Numer of Looks",
                },
                keys: ["numberOfLooksTM", "numberOfLooksYM"],
            },
            ],
        },
        {
            id: 'bar2',
            title: "Hardcore Stacked Bar",
            description: "Chart display to the extent of your imagination",
            footnote: "Source: Transport of London",
            data: [
                {
                  station: "Finsbury\nPark",
                  early: 2454,
                  morningPeak: 16644,
                  interPeak: 9338,
                  afternoonPeak: 6346,
                  evening: 3547,
                },
                {
                  station: "Seven\nSisters",
                  early: 3927,
                  morningPeak: 7581,
                  interPeak: 5421,
                  afternoonPeak: 3245,
                  evening: 2036,
                },
                {
                  station: "Tottenham\nHale",
                  early: 6836,
                  morningPeak: 12740,
                  interPeak: 14964,
                  afternoonPeak: 12790,
                  evening: 8428,
                },
                {
                  station: "Warren\nStreet",
                  early: 9108,
                  morningPeak: 2710,
                  interPeak: 5902,
                  afternoonPeak: 10947,
                  evening: 5574,
                },
                {
                  station: "Oxford\nCircus",
                  early: 7170,
                  morningPeak: 4996,
                  interPeak: 26616,
                  afternoonPeak: 32269,
                  evening: 3665,
                },
                {
                  station: "Green\nPark",
                  early: 6252,
                  morningPeak: 3911,
                  interPeak: 11971,
                  afternoonPeak: 19749,
                  evening: 11582,
                },
              ],
            series: [
                {
                  type: "bar",
                  xKey: "station",
                  yKey: "early",
                  yName: "Early",
                  stacked: true,
                  normalizedTo: 100,
                },
                {
                  type: "bar",
                  xKey: "station",
                  yKey: "morningPeak",
                  yName: "Morning peak",
                  stacked: true,
                  normalizedTo: 100,
                },
                {
                  type: "bar",
                  xKey: "station",
                  yKey: "interPeak",
                  yName: "Between peak",
                  stacked: true,
                  normalizedTo: 100,
                },
                {
                  type: "bar",
                  xKey: "station",
                  yKey: "afternoonPeak",
                  yName: "Afternoon peak",
                  stacked: true,
                  normalizedTo: 100,
                },
                {
                  type: "bar",
                  xKey: "station",
                  yKey: "evening",
                  yName: "Evening",
                  stacked: true,
                  normalizedTo: 100,
                },
              ],
            axes: [
                {
                    type: "category",
                    position: "bottom",
                    paddingInner: 0,
                    groupPaddingInner: 0,
                    paddingOuter: 0,
                },
                {
                    type: "number",
                    position: "left",
                    nice: false,
                    gridLine: {
                    enabled: false,
                    },
                    label: {
                    enabled: false,
                    },
                    crosshair: {
                    enabled: false,
                    },
                },
            ],
            theme: {
                overrides: {
                  bar: {
                    series: {
                      stroke: "transparent",
                      strokeWidth: 2,
                      cornerRadius: 6,
                      fillOpacity: 0.8,
                      label: {
                        enabled: true,
                        formatter: ({ value }) => `${numFormatter.format(value)}`,
                      },
                      tooltip: {
                        renderer: ({ title, datum, xKey, yKey }) => ({
                          title,
                          content: `${datum[xKey]}: ${numFormatter.format(datum[yKey])}`,
                        }),
                      },
                    },
                  },
                },
              },
        },
        {
            id: 'line0',
            title: "Simple Line Graphs",
            description: "A Line Series visualises continuous data, and is typically used to see trends or fluctuations over time.",
            footnote: "Source: Department for Business, Energy & Industrial Strategy",
            data: [{
                date: new Date(2019, 0, 7),
                petrol: 120.27,
                diesel: 130.33,
                lowerPetrol: 119.8,
                upperPetrol: 120.7,
                lowerDiesel: 130.0,
                upperDiesel: 131.5,
              },
              {
                date: new Date(2019, 0, 14),
                petrol: 119.53,
                diesel: 129.47,
                lowerPetrol: 119.0,
                upperPetrol: 120.0,
                lowerDiesel: 128.5,
                upperDiesel: 130.5,
              },
              {
                date: new Date(2019, 0, 21),
                petrol: 119.12,
                diesel: 128.92,
                lowerPetrol: 118.5,
                upperPetrol: 119.8,
                lowerDiesel: 128.0,
                upperDiesel: 129.5,
              },
              {
                date: new Date(2019, 0, 28),
                petrol: 119.29,
                diesel: 129.1,
                lowerPetrol: 118.0,
                upperPetrol: 120,
                lowerDiesel: 128.7,
                upperDiesel: 130.5,
              },
              {
                date: new Date(2019, 1, 4),
                petrol: 119.13,
                diesel: 129.13,
                lowerPetrol: 118.5,
                upperPetrol: 119.9,
                lowerDiesel: 129.0,
                upperDiesel: 131.0,
              },
              {
                date: new Date(2019, 1, 11),
                petrol: 118.97,
                diesel: 129.17,
                lowerPetrol: 118.5,
                upperPetrol: 119.6,
                lowerDiesel: 129.0,
                upperDiesel: 131.5,
              },
              {
                date: new Date(2019, 1, 18),
                petrol: 119.05,
                diesel: 129.23,
                lowerPetrol: 118.5,
                upperPetrol: 119.6,
                lowerDiesel: 129.0,
                upperDiesel: 131.0,
              },
              {
                date: new Date(2019, 1, 25),
                petrol: 119.22,
                diesel: 129.66,
                lowerPetrol: 118.9,
                upperPetrol: 119.7,
                lowerDiesel: 129.0,
                upperDiesel: 131.0,
              },
              {
                date: new Date(2019, 2, 4),
                petrol: 119.72,
                diesel: 130.25,
                lowerPetrol: 119.4,
                upperPetrol: 120.2,
                lowerDiesel: 129.0,
                upperDiesel: 131.5,
              },
              {
                date: new Date(2019, 2, 11),
                petrol: 120.1,
                diesel: 130.59,
                lowerPetrol: 119.9,
                upperPetrol: 120.6,
                lowerDiesel: 130.3,
                upperDiesel: 131.3,
              },
              {
                date: new Date(2019, 2, 18),
                petrol: 120.48,
                diesel: 130.85,
                lowerPetrol: 119.2,
                upperPetrol: 120.9,
                lowerDiesel: 130.5,
                upperDiesel: 131.5,
              },
              {
                date: new Date(2019, 2, 25),
                petrol: 120.83,
                diesel: 131.15,
                lowerPetrol: 119.5,
                upperPetrol: 121.1,
                lowerDiesel: 130.5,
                upperDiesel: 131.7,
              },
              {
                date: new Date(2019, 3, 1),
                petrol: 121.7,
                diesel: 131.48,
                lowerPetrol: 120.4,
                upperPetrol: 123.0,
                lowerDiesel: 131.0,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 3, 8),
                petrol: 122.75,
                diesel: 132.08,
                lowerPetrol: 121.5,
                upperPetrol: 123.2,
                lowerDiesel: 131.5,
                upperDiesel: 133.0,
              },
              {
                date: new Date(2019, 3, 15),
                petrol: 124.06,
                diesel: 132.96,
                lowerPetrol: 122.8,
                upperPetrol: 125.5,
                lowerDiesel: 132.0,
                upperDiesel: 133.5,
              },
              {
                date: new Date(2019, 3, 22),
                petrol: 125.43,
                diesel: 133.99,
                lowerPetrol: 124.1,
                upperPetrol: 126.7,
                lowerDiesel: 133.0,
                upperDiesel: 134.0,
              },
              {
                date: new Date(2019, 3, 29),
                petrol: 126.36,
                diesel: 134.6,
                lowerPetrol: 126.0,
                upperPetrol: 127.5,
                lowerDiesel: 134.0,
                upperDiesel: 135.0,
              },
              {
                date: new Date(2019, 4, 6),
                petrol: 127.5,
                diesel: 135.41,
                lowerPetrol: 127.1,
                upperPetrol: 128.8,
                lowerDiesel: 135.0,
                upperDiesel: 136.0,
              },
              {
                date: new Date(2019, 4, 13),
                petrol: 127.97,
                diesel: 135.36,
                lowerPetrol: 126.7,
                upperPetrol: 129.2,
                lowerDiesel: 135.0,
                upperDiesel: 136.0,
              },
              {
                date: new Date(2019, 4, 20),
                petrol: 128.51,
                diesel: 135.82,
                lowerPetrol: 128.0,
                upperPetrol: 129.8,
                lowerDiesel: 135.0,
                upperDiesel: 136.0,
              },
              {
                date: new Date(2019, 4, 27),
                petrol: 129.14,
                diesel: 136.45,
                lowerPetrol: 128.9,
                upperPetrol: 129.4,
                lowerDiesel: 136.0,
                upperDiesel: 137.0,
              },
              {
                date: new Date(2019, 5, 3),
                petrol: 129.41,
                diesel: 136.39,
                lowerPetrol: 129.1,
                upperPetrol: 129.7,
                lowerDiesel: 136.0,
                upperDiesel: 137.0,
              },
              {
                date: new Date(2019, 5, 10),
                petrol: 128.89,
                diesel: 135.4,
                lowerPetrol: 128.6,
                upperPetrol: 129.1,
                lowerDiesel: 135.0,
                upperDiesel: 136.0,
              },
              {
                date: new Date(2019, 5, 17),
                petrol: 127.66,
                diesel: 133.76,
                lowerPetrol: 127.3,
                upperPetrol: 128.0,
                lowerDiesel: 133.0,
                upperDiesel: 134.0,
              },
              {
                date: new Date(2019, 5, 24),
                petrol: 126.66,
                diesel: 131.81,
                lowerPetrol: 126.3,
                upperPetrol: 127.0,
                lowerDiesel: 130.5,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 6, 1),
                petrol: 126.49,
                diesel: 131.55,
                lowerPetrol: 126.2,
                upperPetrol: 126.8,
                lowerDiesel: 131.0,
                upperDiesel: 133.0,
              },
              {
                date: new Date(2019, 6, 8),
                petrol: 126.86,
                diesel: 131.68,
                lowerPetrol: 126.6,
                upperPetrol: 127.1,
                lowerDiesel: 131.5,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 6, 15),
                petrol: 127.13,
                diesel: 131.86,
                lowerPetrol: 126.9,
                upperPetrol: 127.4,
                lowerDiesel: 130.8,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 6, 22),
                petrol: 127.81,
                diesel: 132.21,
                lowerPetrol: 127.6,
                upperPetrol: 128.1,
                lowerDiesel: 131.8,
                upperDiesel: 133.9,
              },
              {
                date: new Date(2019, 6, 29),
                petrol: 128.03,
                diesel: 132.6,
                lowerPetrol: 127.8,
                upperPetrol: 128.3,
                lowerDiesel: 131.6,
                upperDiesel: 133.0,
              },
              {
                date: new Date(2019, 7, 5),
                petrol: 128.37,
                diesel: 132.61,
                lowerPetrol: 128.1,
                upperPetrol: 128.6,
                lowerDiesel: 132.0,
                upperDiesel: 133.2,
              },
              {
                date: new Date(2019, 7, 12),
                petrol: 128.36,
                diesel: 132.59,
                lowerPetrol: 128.1,
                upperPetrol: 128.6,
                lowerDiesel: 132.3,
                upperDiesel: 133.0,
              },
              {
                date: new Date(2019, 7, 19),
                petrol: 128.17,
                diesel: 132.6,
                lowerPetrol: 127.9,
                upperPetrol: 128.4,
                lowerDiesel: 132.0,
                upperDiesel: 133.0,
              },
              {
                date: new Date(2019, 7, 26),
                petrol: 128.22,
                diesel: 132.51,
                lowerPetrol: 128.0,
                upperPetrol: 128.4,
                lowerDiesel: 132.0,
                upperDiesel: 133.0,
              },
              {
                date: new Date(2019, 8, 2),
                petrol: 127.86,
                diesel: 132.29,
                lowerPetrol: 127.6,
                upperPetrol: 128.1,
                lowerDiesel: 132.0,
                upperDiesel: 133.0,
              },
              {
                date: new Date(2019, 8, 9),
                petrol: 127.79,
                diesel: 131.89,
                lowerPetrol: 127.6,
                upperPetrol: 128.1,
                lowerDiesel: 131.5,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 8, 16),
                petrol: 126.92,
                diesel: 131.35,
                lowerPetrol: 126.7,
                upperPetrol: 127.2,
                lowerDiesel: 131.0,
                upperDiesel: 131.7,
              },
              {
                date: new Date(2019, 8, 23),
                petrol: 126.78,
                diesel: 131.52,
                lowerPetrol: 126.5,
                upperPetrol: 127.0,
                lowerDiesel: 131.0,
                upperDiesel: 131.7,
              },
              {
                date: new Date(2019, 8, 30),
                petrol: 126.92,
                diesel: 131.83,
                lowerPetrol: 126.7,
                upperPetrol: 127.2,
                lowerDiesel: 131.0,
                upperDiesel: 131.85,
              },
              {
                date: new Date(2019, 9, 7),
                petrol: 126.87,
                diesel: 131.82,
                lowerPetrol: 126.6,
                upperPetrol: 127.1,
                lowerDiesel: 131.0,
                upperDiesel: 131.88,
              },
              {
                date: new Date(2019, 9, 14),
                petrol: 126.62,
                diesel: 131.58,
                lowerPetrol: 126,
                upperPetrol: 126.9,
                lowerDiesel: 131.2,
                upperDiesel: 131.9,
              },
              {
                date: new Date(2019, 9, 21),
                petrol: 126.72,
                diesel: 131.48,
                lowerPetrol: 126.5,
                upperPetrol: 127.0,
                lowerDiesel: 131.2,
                upperDiesel: 131.9,
              },
              {
                date: new Date(2019, 9, 28),
                petrol: 126.75,
                diesel: 131.47,
                lowerPetrol: 126.5,
                upperPetrol: 127.0,
                lowerDiesel: 131.2,
                upperDiesel: 131.9,
              },
              {
                date: new Date(2019, 10, 4),
                petrol: 127.07,
                diesel: 131.6,
                lowerPetrol: 126.9,
                upperPetrol: 127.2,
                lowerDiesel: 131.3,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 10, 11),
                petrol: 127.03,
                diesel: 131.58,
                lowerPetrol: 126.9,
                upperPetrol: 127.2,
                lowerDiesel: 131.3,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 10, 18),
                petrol: 127.01,
                diesel: 131.57,
                lowerPetrol: 126.8,
                upperPetrol: 127.1,
                lowerDiesel: 131.3,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 10, 25),
                petrol: 127.09,
                diesel: 131.6,
                lowerPetrol: 126.9,
                upperPetrol: 127.2,
                lowerDiesel: 131.3,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 11, 2),
                petrol: 127.02,
                diesel: 131.55,
                lowerPetrol: 126.8,
                upperPetrol: 127.1,
                lowerDiesel: 131.3,
                upperDiesel: 132.0,
              },
              {
                date: new Date(2019, 11, 9),
                petrol: 126.78,
                diesel: 131.36,
                lowerPetrol: 126.6,
                upperPetrol: 127.0,
                lowerDiesel: 131.2,
                upperDiesel: 131.9,
              },
              {
                date: new Date(2019, 11, 16),
                petrol: 126.56,
                diesel: 131.2,
                lowerPetrol: 126.4,
                upperPetrol: 126.9,
                lowerDiesel: 131.1,
                upperDiesel: 131.8,
              },
              {
                date: new Date(2019, 11, 23),
                petrol: 126.4,
                diesel: 131.07,
                lowerPetrol: 126.2,
                upperPetrol: 126.7,
                lowerDiesel: 131.0,
                upperDiesel: 131.7,
              },
              {
                date: new Date(2019, 11, 30),
                petrol: 126.19,
                diesel: 130.88,
                lowerPetrol: 125.9,
                upperPetrol: 126.4,
                lowerDiesel: 130.8,
                upperDiesel: 131.3,
              }],
            series: [
                {
                  type: "line",
                  xKey: "date",
                  yKey: "petrol",
                  tooltip,
                },
                {
                  type: "line",
                  xKey: "date",
                  yKey: "diesel",
                  tooltip,
                },
              ],
            axes: [
                {
                  position: "bottom",
                  type: "time",
                  title: {
                    text: "Date",
                  },
                  label: {
                    format: "%b",
                  },
                },
                {
                  position: "left",
                  type: "number",
                  title: {
                    text: "Price in Pence",
                  },
                },
              ],
        },
        {
            id: 'line1',
            title: "Line Graph With Gaps",
            description: "When you have non-continuous graphs",
            footnote: "Source: Department of Environment, Food and Rural Affairs",
            data: [
                {
                  week: 1,
                  belize: 0.66,
                  columbia: 0.97,
                  costaRica: 0.98,
                  ecuador: 0.88,
                  panama: 0.96,
                  guatemala: 0.94,
                },
                {
                  week: 2,
                  belize: 0.66,
                  columbia: 0.96,
                  costaRica: 0.97,
                  ecuador: 0.88,
                  panama: 0.96,
                  guatemala: 0.94,
                },
                {
                  week: 3,
                  belize: 1,
                  columbia: 1.06,
                  costaRica: 0.99,
                  ecuador: 0.88,
                  panama: 0.96,
                  guatemala: 0.96,
                },
                {
                  week: 4,
                  belize: 0.88,
                  columbia: 1.06,
                  costaRica: 1,
                  ecuador: 0.93,
                  panama: 0.96,
                  guatemala: 0.99,
                },
                {
                  week: 5,
                  columbia: 1.06,
                  costaRica: 1.04,
                  ecuador: 1.06,
                  ivoryCoast: 0.9,
                  panama: 1.08,
                  guatemala: 1.01,
                },
                {
                  week: 6,
                  columbia: 0.94,
                  costaRica: 1,
                  ecuador: 0.93,
                  panama: 1.05,
                  guatemala: 0.96,
                  nicaragua: 0.86,
                },
                {
                  week: 7,
                  columbia: 0.95,
                  costaRica: 1,
                  ecuador: 0.93,
                  panama: 1.05,
                  guatemala: 0.97,
                  nicaragua: 0.86,
                },
                {
                  week: 8,
                  belize: 1.06,
                  columbia: 0.94,
                  costaRica: 0.98,
                  ecuador: 0.93,
                  panama: 1.05,
                  guatemala: 0.96,
                },
                {
                  week: 9,
                  columbia: 0.93,
                  costaRica: 0.97,
                  ecuador: 0.93,
                  panama: 1.05,
                  guatemala: 0.93,
                },
                {
                  week: 10,
                  columbia: 0.96,
                  costaRica: 0.99,
                  ecuador: 0.96,
                  panama: 1.05,
                  guatemala: 0.97,
                },
                {
                  week: 11,
                  columbia: 0.95,
                  costaRica: 0.99,
                  ecuador: 0.96,
                  panama: 0.99,
                  guatemala: 0.97,
                },
                {
                  week: 12,
                  columbia: 0.95,
                  costaRica: 0.99,
                  ecuador: 0.96,
                  panama: 0.9,
                  guatemala: 0.97,
                },
                {
                  week: 13,
                  columbia: 0.95,
                  costaRica: 1,
                  ecuador: 0.96,
                  panama: 0.9,
                  guatemala: 0.97,
                },
                {
                  week: 14,
                  columbia: 0.88,
                  costaRica: 0.97,
                  ecuador: 0.96,
                  panama: 0.9,
                  guatemala: 0.96,
                },
                {
                  week: 15,
                  columbia: 0.97,
                  costaRica: 1,
                  ecuador: 0.96,
                  panama: 0.9,
                  guatemala: 0.98,
                },
                {
                  week: 16,
                  columbia: 0.97,
                  costaRica: 1,
                  ecuador: 0.96,
                  panama: 0.9,
                  guatemala: 0.97,
                },
                {
                  week: 17,
                  columbia: 0.93,
                  costaRica: 1.01,
                  ecuador: 0.96,
                  panama: 0.9,
                  guatemala: 0.96,
                },
                {
                  week: 18,
                  columbia: 0.96,
                  costaRica: 1.01,
                  ecuador: 0.9,
                  panama: 0.9,
                  guatemala: 1.01,
                },
                {
                  week: 19,
                  columbia: 0.96,
                  costaRica: 1.01,
                  ecuador: 0.9,
                  panama: 0.9,
                  guatemala: 1.01,
                },
                {
                  week: 20,
                  belize: 0.68,
                  columbia: 0.93,
                  costaRica: 0.99,
                  ecuador: 0.94,
                  panama: 0.9,
                  guatemala: 1.01,
                },
                {
                  week: 21,
                  belize: 0.68,
                  columbia: 0.93,
                  costaRica: 0.97,
                  ecuador: 0.94,
                  panama: 0.94,
                  guatemala: 1.01,
                  nicaragua: 0.99,
                },
                {
                  week: 22,
                  belize: 0.68,
                  columbia: 0.85,
                  costaRica: 0.98,
                  ecuador: 0.81,
                  ivoryCoast: 0.92,
                  panama: 0.94,
                  nicaragua: 0.99,
                },
                {
                  week: 23,
                  belize: 0.68,
                  columbia: 0.94,
                  costaRica: 1.02,
                  ecuador: 0.94,
                  panama: 0.99,
                  guatemala: 1.01,
                  nicaragua: 0.99,
                },
                {
                  week: 24,
                  belize: 0.68,
                  columbia: 0.94,
                  costaRica: 1.02,
                  ecuador: 0.94,
                  ivoryCoast: 0.97,
                  panama: 0.99,
                  guatemala: 1.01,
                  nicaragua: 0.99,
                },
                {
                  week: 25,
                  belize: 0.68,
                  columbia: 0.94,
                  costaRica: 1.01,
                  ecuador: 0.94,
                  panama: 0.99,
                  guatemala: 0.97,
                  nicaragua: 0.81,
                },
                {
                  week: 26,
                  belize: 0.68,
                  columbia: 0.9,
                  costaRica: 0.92,
                  ecuador: 0.85,
                  panama: 0.95,
                },
                {
                  week: 27,
                  belize: 0.7,
                  columbia: 0.9,
                  costaRica: 0.95,
                  ecuador: 0.81,
                  guatemala: 0.86,
                },
                {
                  week: 28,
                  belize: 0.9,
                  columbia: 0.93,
                  costaRica: 0.96,
                  ecuador: 0.9,
                  ivoryCoast: 0.93,
                  panama: 0.93,
                  guatemala: 1.01,
                },
                {
                  week: 29,
                  belize: 0.9,
                  columbia: 0.96,
                  costaRica: 0.96,
                  ecuador: 0.96,
                  ivoryCoast: 0.93,
                  panama: 0.99,
                  guatemala: 1.01,
                },
                {
                  week: 30,
                  belize: 0.95,
                  columbia: 0.97,
                  costaRica: 1.05,
                  ecuador: 0.96,
                  ivoryCoast: 0.99,
                  guatemala: 1.01,
                },
                {
                  week: 31,
                  belize: 1.06,
                  columbia: 1.06,
                  costaRica: 1.05,
                  ecuador: 1.02,
                  ivoryCoast: 0.99,
                  guatemala: 1.01,
                },
                {
                  week: 32,
                  belize: 1.06,
                  columbia: 1.04,
                  costaRica: 1.07,
                  dominicanRepublic: 0.84,
                  ecuador: 1.1,
                  guatemala: 1.01,
                },
                {
                  week: 33,
                  belize: 1.06,
                  columbia: 1.06,
                  costaRica: 1.06,
                  dominicanRepublic: 0.84,
                  ecuador: 1.1,
                  guatemala: 0.97,
                },
                {
                  week: 34,
                  belize: 1.06,
                  columbia: 1.08,
                  costaRica: 1.08,
                  ecuador: 1.1,
                  guatemala: 1,
                },
                {
                  week: 35,
                  columbia: 1.08,
                  costaRica: 1.08,
                  ecuador: 1.1,
                  guatemala: 1,
                },
                {
                  week: 36,
                  columbia: 1.1,
                  costaRica: 1.07,
                  honduras: 1.1,
                  guatemala: 0.97,
                  nicaragua: 1.1,
                },
                {
                  week: 37,
                  columbia: 1.1,
                  costaRica: 1.07,
                  honduras: 1.1,
                  guatemala: 0.97,
                  nicaragua: 1.1,
                },
                {
                  week: 38,
                  columbia: 1.1,
                  costaRica: 1.07,
                  honduras: 1.1,
                  ivoryCoast: 0.84,
                  guatemala: 0.99,
                  nicaragua: 1.1,
                },
                {
                  week: 39,
                  columbia: 1.07,
                  costaRica: 1.06,
                  ivoryCoast: 0.97,
                  guatemala: 1.01,
                },
                {
                  week: 40,
                  columbia: 0.95,
                  costaRica: 1.01,
                  ivoryCoast: 0.97,
                  panama: 0.95,
                  guatemala: 1.01,
                },
                {
                  week: 41,
                  costaRica: 1.05,
                  ivoryCoast: 0.97,
                  guatemala: 1.01,
                },
                {
                  week: 42,
                  costaRica: 1.09,
                  ivoryCoast: 0.97,
                  guatemala: 1.01,
                },
                {
                  week: 43,
                  columbia: 1.12,
                  costaRica: 1.07,
                  ivoryCoast: 0.97,
                  panama: 1.12,
                  guatemala: 1.01,
                },
                {
                  week: 44,
                  columbia: 1.09,
                  costaRica: 1.06,
                  guatemala: 1.01,
                },
                {
                  week: 45,
                  columbia: 1.12,
                  costaRica: 0.99,
                  ecuador: 1.12,
                  panama: 1.1,
                },
                {
                  week: 46,
                  columbia: 0.77,
                  costaRica: 0.79,
                  ecuador: 0.88,
                  ivoryCoast: 0.88,
                  panama: 0.88,
                },
                {
                  week: 47,
                  columbia: 0.97,
                  costaRica: 1.03,
                  ecuador: 0.88,
                  ivoryCoast: 0.79,
                  panama: 0.99,
                  guatemala: 0.91,
                },
                {
                  week: 48,
                  cameroon: 0.66,
                  columbia: 0.97,
                  costaRica: 1,
                  ecuador: 0.85,
                  panama: 0.99,
                  guatemala: 0.82,
                },
                {
                  week: 49,
                  costaRica: 1.02,
                  dominicanRepublic: 0.77,
                  guatemala: 0.99,
                },
              ],
            series: [
                {
                  type: "line",
                  xKey: "week",
                  yKey: "belize",
                  yName: "Belize",
                },
                {
                  type: "line",
                  xKey: "week",
                  yKey: "cameroon",
                  yName: "Cameroon",
                },
                {
                  type: "line",
                  xKey: "week",
                  yKey: "columbia",
                  yName: "Columbia",
                },
                {
                  type: "line",
                  xKey: "week",
                  yKey: "costaRica",
                  yName: "Costa Rica",
                },
                {
                  type: "line",
                  xKey: "week",
                  yKey: "dominicanRepublic",
                  yName: "Dominican Republic",
                },
                {
                  type: "line",
                  xKey: "week",
                  yKey: "ecuador",
                  yName: "Ecuador",
                },
                {
                  type: "line",
                  xKey: "week",
                  yKey: "honduras",
                  yName: "Honduras",
                },
                {
                  type: "line",
                  xKey: "week",
                  yKey: "ivoryCoast",
                  yName: "Ivory Coast",
                },
                {
                  type: "line",
                  xKey: "week",
                  yKey: "panama",
                  yName: "Panama",
                },
                {
                  type: "line",
                  xKey: "week",
                  yKey: "nicaragua",
                  yName: "Nicaragua",
                },
              ],
            axes: [
                {
                  type: "category",
                  position: "bottom",
                  title: {
                    text: "Week",
                  },
                  label: {
                    formatter: (params) => (params.index % 3 ? "" : params.value),
                  },
                },
                {
                  type: "number",
                  position: "left",
                  title: {
                    text: "£ per kg",
                  },
                },
            ],
        },
        {
            id: 'line2',
            title: "Multi Line",
            description: "Multi line continuous data",
            footnote: "Source: American Time Use Survey 2022",
            data: [
                {
                  age: 15,
                  timeSpentAlone: 193.30588,
                  timeSpentWithFriends: 109.4145,
                  timeSpentWithChildren: 23.463852,
                  timeSpentWithFamily: 267.12091,
                  timeSpentWithPartner: 0,
                  timeSpentWithCoworkers: 8.3420067,
                },
                {
                  age: 16,
                  timeSpentAlone: 206.37056,
                  timeSpentWithFriends: 110.7418,
                  timeSpentWithChildren: 28.609867,
                  timeSpentWithFamily: 254.3381,
                  timeSpentWithPartner: 0.030690858,
                  timeSpentWithCoworkers: 23.529137,
                },
                {
                  age: 17,
                  timeSpentAlone: 224.17331,
                  timeSpentWithFriends: 120.41887,
                  timeSpentWithChildren: 26.089708,
                  timeSpentWithFamily: 229.81561,
                  timeSpentWithPartner: 1.1228406,
                  timeSpentWithCoworkers: 43.809685,
                },
                {
                  age: 18,
                  timeSpentAlone: 242.69839,
                  timeSpentWithFriends: 137.75107,
                  timeSpentWithChildren: 27.387308,
                  timeSpentWithFamily: 236.35201,
                  timeSpentWithPartner: 5.6972671,
                  timeSpentWithCoworkers: 81.633575,
                },
                {
                  age: 19,
                  timeSpentAlone: 267.79385,
                  timeSpentWithFriends: 129.85716,
                  timeSpentWithChildren: 36.445004,
                  timeSpentWithFamily: 201.2766,
                  timeSpentWithPartner: 19.341291,
                  timeSpentWithCoworkers: 124.85052,
                },
                {
                  age: 20,
                  timeSpentAlone: 277.60379,
                  timeSpentWithFriends: 122.7402,
                  timeSpentWithChildren: 54.630512,
                  timeSpentWithFamily: 173.13503,
                  timeSpentWithPartner: 26.35417,
                  timeSpentWithCoworkers: 143.9003,
                },
                {
                  age: 21,
                  timeSpentAlone: 270.21817,
                  timeSpentWithFriends: 122.40627,
                  timeSpentWithChildren: 69.293869,
                  timeSpentWithFamily: 152.67331,
                  timeSpentWithPartner: 59.897781,
                  timeSpentWithCoworkers: 154.20972,
                },
                {
                  age: 22,
                  timeSpentAlone: 283.56686,
                  timeSpentWithFriends: 100.16862,
                  timeSpentWithChildren: 72.302246,
                  timeSpentWithFamily: 135.8266,
                  timeSpentWithPartner: 55.767094,
                  timeSpentWithCoworkers: 173.0473,
                },
                {
                  age: 23,
                  timeSpentAlone: 270.93015,
                  timeSpentWithFriends: 101.07177,
                  timeSpentWithChildren: 96.935883,
                  timeSpentWithFamily: 125.79333,
                  timeSpentWithPartner: 78.188667,
                  timeSpentWithCoworkers: 190.10524,
                },
                {
                  age: 24,
                  timeSpentAlone: 265.81378,
                  timeSpentWithFriends: 96.786346,
                  timeSpentWithChildren: 99.394424,
                  timeSpentWithFamily: 103.75845,
                  timeSpentWithPartner: 99.44416,
                  timeSpentWithCoworkers: 206.05486,
                },
                {
                  age: 25,
                  timeSpentAlone: 275.12906,
                  timeSpentWithFriends: 77.543015,
                  timeSpentWithChildren: 119.50971,
                  timeSpentWithFamily: 101.02744,
                  timeSpentWithPartner: 121.25083,
                  timeSpentWithCoworkers: 199.20917,
                },
                {
                  age: 26,
                  timeSpentAlone: 281.63202,
                  timeSpentWithFriends: 77.856834,
                  timeSpentWithChildren: 128.59393,
                  timeSpentWithFamily: 87.654915,
                  timeSpentWithPartner: 139.91745,
                  timeSpentWithCoworkers: 190.09406,
                },
                {
                  age: 27,
                  timeSpentAlone: 259.3331,
                  timeSpentWithFriends: 74.140686,
                  timeSpentWithChildren: 153.33383,
                  timeSpentWithFamily: 85.956535,
                  timeSpentWithPartner: 151.88562,
                  timeSpentWithCoworkers: 211.48781,
                },
                {
                  age: 28,
                  timeSpentAlone: 261.13989,
                  timeSpentWithFriends: 62.491688,
                  timeSpentWithChildren: 175.83809,
                  timeSpentWithFamily: 80.147217,
                  timeSpentWithPartner: 168.24556,
                  timeSpentWithCoworkers: 212.14497,
                },
                {
                  age: 29,
                  timeSpentAlone: 253.66589,
                  timeSpentWithFriends: 55.084454,
                  timeSpentWithChildren: 194.49931,
                  timeSpentWithFamily: 81.6101,
                  timeSpentWithPartner: 176.19919,
                  timeSpentWithCoworkers: 199.11349,
                },
                {
                  age: 30,
                  timeSpentAlone: 250.02524,
                  timeSpentWithFriends: 53.478016,
                  timeSpentWithChildren: 199.76436,
                  timeSpentWithFamily: 72.476334,
                  timeSpentWithPartner: 180.02309,
                  timeSpentWithCoworkers: 215.61365,
                },
                {
                  age: 31,
                  timeSpentAlone: 253.16542,
                  timeSpentWithFriends: 50.925926,
                  timeSpentWithChildren: 225.92371,
                  timeSpentWithFamily: 69.526543,
                  timeSpentWithPartner: 203.71202,
                  timeSpentWithCoworkers: 199.06003,
                },
                {
                  age: 32,
                  timeSpentAlone: 255.07323,
                  timeSpentWithFriends: 49.464462,
                  timeSpentWithChildren: 230.71593,
                  timeSpentWithFamily: 61.336475,
                  timeSpentWithPartner: 192.00175,
                  timeSpentWithCoworkers: 202.76134,
                },
                {
                  age: 33,
                  timeSpentAlone: 244.90091,
                  timeSpentWithFriends: 49.731628,
                  timeSpentWithChildren: 256.41312,
                  timeSpentWithFamily: 66.359383,
                  timeSpentWithPartner: 200.02365,
                  timeSpentWithCoworkers: 186.96373,
                },
                {
                  age: 34,
                  timeSpentAlone: 263.59116,
                  timeSpentWithFriends: 42.650288,
                  timeSpentWithChildren: 261.18497,
                  timeSpentWithFamily: 65.723053,
                  timeSpentWithPartner: 199.23759,
                  timeSpentWithCoworkers: 179.36411,
                },
                {
                  age: 35,
                  timeSpentAlone: 262.62488,
                  timeSpentWithFriends: 41.661636,
                  timeSpentWithChildren: 248.93806,
                  timeSpentWithFamily: 62.107143,
                  timeSpentWithPartner: 198.27702,
                  timeSpentWithCoworkers: 190.68065,
                },
                {
                  age: 36,
                  timeSpentAlone: 273.27942,
                  timeSpentWithFriends: 40.120937,
                  timeSpentWithChildren: 256.59799,
                  timeSpentWithFamily: 64.809921,
                  timeSpentWithPartner: 197.55948,
                  timeSpentWithCoworkers: 178.94667,
                },
                {
                  age: 37,
                  timeSpentAlone: 267.09787,
                  timeSpentWithFriends: 43.362503,
                  timeSpentWithChildren: 256.37634,
                  timeSpentWithFamily: 56.446011,
                  timeSpentWithPartner: 204.00514,
                  timeSpentWithCoworkers: 188.47969,
                },
                {
                  age: 38,
                  timeSpentAlone: 258.99704,
                  timeSpentWithFriends: 42.101093,
                  timeSpentWithChildren: 254.45975,
                  timeSpentWithFamily: 54.001514,
                  timeSpentWithPartner: 203.30919,
                  timeSpentWithCoworkers: 197.09261,
                },
                {
                  age: 39,
                  timeSpentAlone: 281.98877,
                  timeSpentWithFriends: 33.611919,
                  timeSpentWithChildren: 266.07874,
                  timeSpentWithFamily: 52.701588,
                  timeSpentWithPartner: 212.07637,
                  timeSpentWithCoworkers: 172.79756,
                },
                {
                  age: 40,
                  timeSpentAlone: 278.25668,
                  timeSpentWithFriends: 36.197014,
                  timeSpentWithChildren: 242.43935,
                  timeSpentWithFamily: 54.638985,
                  timeSpentWithPartner: 201.94627,
                  timeSpentWithCoworkers: 187.34126,
                },
                {
                  age: 41,
                  timeSpentAlone: 292.07227,
                  timeSpentWithFriends: 38.729492,
                  timeSpentWithChildren: 237.29298,
                  timeSpentWithFamily: 55.611694,
                  timeSpentWithPartner: 194.68652,
                  timeSpentWithCoworkers: 179.37498,
                },
                {
                  age: 42,
                  timeSpentAlone: 297.90939,
                  timeSpentWithFriends: 38.695633,
                  timeSpentWithChildren: 222.96886,
                  timeSpentWithFamily: 50.690075,
                  timeSpentWithPartner: 182.25496,
                  timeSpentWithCoworkers: 189.4864,
                },
                {
                  age: 43,
                  timeSpentAlone: 321.74783,
                  timeSpentWithFriends: 39.107994,
                  timeSpentWithChildren: 207.65651,
                  timeSpentWithFamily: 55.288914,
                  timeSpentWithPartner: 181.83145,
                  timeSpentWithCoworkers: 169.79688,
                },
                {
                  age: 44,
                  timeSpentAlone: 312.69861,
                  timeSpentWithFriends: 38.859802,
                  timeSpentWithChildren: 207.01961,
                  timeSpentWithFamily: 54.224209,
                  timeSpentWithPartner: 191.94835,
                  timeSpentWithCoworkers: 182.13411,
                },
                {
                  age: 45,
                  timeSpentAlone: 309.03583,
                  timeSpentWithFriends: 36.090996,
                  timeSpentWithChildren: 199.21028,
                  timeSpentWithFamily: 58.068977,
                  timeSpentWithPartner: 183.99062,
                  timeSpentWithCoworkers: 182.52716,
                },
                {
                  age: 46,
                  timeSpentAlone: 326.78207,
                  timeSpentWithFriends: 37.459354,
                  timeSpentWithChildren: 177.52652,
                  timeSpentWithFamily: 54.798512,
                  timeSpentWithPartner: 186.65195,
                  timeSpentWithCoworkers: 179.01489,
                },
                {
                  age: 47,
                  timeSpentAlone: 338.24756,
                  timeSpentWithFriends: 39.243477,
                  timeSpentWithChildren: 168.4313,
                  timeSpentWithFamily: 60.089104,
                  timeSpentWithPartner: 181.05563,
                  timeSpentWithCoworkers: 171.43033,
                },
                {
                  age: 48,
                  timeSpentAlone: 332.5762,
                  timeSpentWithFriends: 33.357357,
                  timeSpentWithChildren: 157.297,
                  timeSpentWithFamily: 58.556328,
                  timeSpentWithPartner: 197.96497,
                  timeSpentWithCoworkers: 170.06847,
                },
                {
                  age: 49,
                  timeSpentAlone: 339.72601,
                  timeSpentWithFriends: 37.315029,
                  timeSpentWithChildren: 132.68301,
                  timeSpentWithFamily: 58.63641,
                  timeSpentWithPartner: 194.11002,
                  timeSpentWithCoworkers: 187.72957,
                },
                {
                  age: 50,
                  timeSpentAlone: 361.14328,
                  timeSpentWithFriends: 28.917883,
                  timeSpentWithChildren: 132.44537,
                  timeSpentWithFamily: 65.362938,
                  timeSpentWithPartner: 174.92821,
                  timeSpentWithCoworkers: 168.1844,
                },
                {
                  age: 51,
                  timeSpentAlone: 368.59146,
                  timeSpentWithFriends: 35.627602,
                  timeSpentWithChildren: 123.67976,
                  timeSpentWithFamily: 62.211754,
                  timeSpentWithPartner: 187.80592,
                  timeSpentWithCoworkers: 172.19505,
                },
                {
                  age: 52,
                  timeSpentAlone: 380.84085,
                  timeSpentWithFriends: 33.961197,
                  timeSpentWithChildren: 102.66885,
                  timeSpentWithFamily: 65.243996,
                  timeSpentWithPartner: 190.51634,
                  timeSpentWithCoworkers: 176.08771,
                },
                {
                  age: 53,
                  timeSpentAlone: 372.17041,
                  timeSpentWithFriends: 31.585169,
                  timeSpentWithChildren: 102.3604,
                  timeSpentWithFamily: 59.573872,
                  timeSpentWithPartner: 188.71446,
                  timeSpentWithCoworkers: 168.29805,
                },
                {
                  age: 54,
                  timeSpentAlone: 377.70459,
                  timeSpentWithFriends: 34.837147,
                  timeSpentWithChildren: 89.755821,
                  timeSpentWithFamily: 60.021786,
                  timeSpentWithPartner: 182.8898,
                  timeSpentWithCoworkers: 184.43581,
                },
                {
                  age: 55,
                  timeSpentAlone: 384.14532,
                  timeSpentWithFriends: 33.079144,
                  timeSpentWithChildren: 88.129921,
                  timeSpentWithFamily: 60.739655,
                  timeSpentWithPartner: 184.38846,
                  timeSpentWithCoworkers: 162.92227,
                },
                {
                  age: 56,
                  timeSpentAlone: 387.00711,
                  timeSpentWithFriends: 36.820248,
                  timeSpentWithChildren: 78.608688,
                  timeSpentWithFamily: 66.083549,
                  timeSpentWithPartner: 195.93608,
                  timeSpentWithCoworkers: 154.11407,
                },
                {
                  age: 57,
                  timeSpentAlone: 399.18466,
                  timeSpentWithFriends: 31.479084,
                  timeSpentWithChildren: 73.898285,
                  timeSpentWithFamily: 58.831005,
                  timeSpentWithPartner: 185.31619,
                  timeSpentWithCoworkers: 157.73422,
                },
                {
                  age: 58,
                  timeSpentAlone: 409.77731,
                  timeSpentWithFriends: 35.2756,
                  timeSpentWithChildren: 68.309761,
                  timeSpentWithFamily: 65.851311,
                  timeSpentWithPartner: 186.54398,
                  timeSpentWithCoworkers: 140.36014,
                },
                {
                  age: 59,
                  timeSpentAlone: 411.51978,
                  timeSpentWithFriends: 29.068735,
                  timeSpentWithChildren: 70.334312,
                  timeSpentWithFamily: 67.322807,
                  timeSpentWithPartner: 199.87039,
                  timeSpentWithCoworkers: 140.17371,
                },
                {
                  age: 60,
                  timeSpentAlone: 413.32019,
                  timeSpentWithFriends: 35.94643,
                  timeSpentWithChildren: 61.933525,
                  timeSpentWithFamily: 65.528786,
                  timeSpentWithPartner: 204.63687,
                  timeSpentWithCoworkers: 125.92768,
                },
                {
                  age: 61,
                  timeSpentAlone: 414.82727,
                  timeSpentWithFriends: 32.807606,
                  timeSpentWithChildren: 71.07634,
                  timeSpentWithFamily: 60.896008,
                  timeSpentWithPartner: 205.22923,
                  timeSpentWithCoworkers: 126.77782,
                },
                {
                  age: 62,
                  timeSpentAlone: 425.2204,
                  timeSpentWithFriends: 34.453568,
                  timeSpentWithChildren: 57.484367,
                  timeSpentWithFamily: 56.583904,
                  timeSpentWithPartner: 224.05167,
                  timeSpentWithCoworkers: 96.651878,
                },
                {
                  age: 63,
                  timeSpentAlone: 430.51068,
                  timeSpentWithFriends: 36.147518,
                  timeSpentWithChildren: 62.510818,
                  timeSpentWithFamily: 73.459251,
                  timeSpentWithPartner: 232.44521,
                  timeSpentWithCoworkers: 78.317001,
                },
                {
                  age: 64,
                  timeSpentAlone: 449.01306,
                  timeSpentWithFriends: 35.180847,
                  timeSpentWithChildren: 55.407318,
                  timeSpentWithFamily: 63.962303,
                  timeSpentWithPartner: 231.84886,
                  timeSpentWithCoworkers: 78.246071,
                },
                {
                  age: 65,
                  timeSpentAlone: 444.02954,
                  timeSpentWithFriends: 35.90049,
                  timeSpentWithChildren: 57.586105,
                  timeSpentWithFamily: 65.28495,
                  timeSpentWithPartner: 242.53215,
                  timeSpentWithCoworkers: 62.186493,
                },
                {
                  age: 66,
                  timeSpentAlone: 431.98727,
                  timeSpentWithFriends: 40.828274,
                  timeSpentWithChildren: 59.682854,
                  timeSpentWithFamily: 69.281334,
                  timeSpentWithPartner: 255.86,
                  timeSpentWithCoworkers: 50.919098,
                },
                {
                  age: 67,
                  timeSpentAlone: 433.85413,
                  timeSpentWithFriends: 38.98082,
                  timeSpentWithChildren: 62.771469,
                  timeSpentWithFamily: 58.832348,
                  timeSpentWithPartner: 258.14743,
                  timeSpentWithCoworkers: 44.558029,
                },
                {
                  age: 68,
                  timeSpentAlone: 448.22601,
                  timeSpentWithFriends: 41.382526,
                  timeSpentWithChildren: 53.818981,
                  timeSpentWithFamily: 53.716782,
                  timeSpentWithPartner: 260.36365,
                  timeSpentWithCoworkers: 39.273418,
                },
                {
                  age: 69,
                  timeSpentAlone: 443.00061,
                  timeSpentWithFriends: 42.001629,
                  timeSpentWithChildren: 68.845222,
                  timeSpentWithFamily: 61.424671,
                  timeSpentWithPartner: 270.69342,
                  timeSpentWithCoworkers: 27.190746,
                },
                {
                  age: 70,
                  timeSpentAlone: 448.85193,
                  timeSpentWithFriends: 45.80217,
                  timeSpentWithChildren: 52.782196,
                  timeSpentWithFamily: 47.977863,
                  timeSpentWithPartner: 261.86359,
                  timeSpentWithCoworkers: 26.851473,
                },
                {
                  age: 71,
                  timeSpentAlone: 444.47784,
                  timeSpentWithFriends: 44.433987,
                  timeSpentWithChildren: 59.073078,
                  timeSpentWithFamily: 58.145714,
                  timeSpentWithPartner: 266.694,
                  timeSpentWithCoworkers: 21.892221,
                },
                {
                  age: 72,
                  timeSpentAlone: 474.45526,
                  timeSpentWithFriends: 44.234802,
                  timeSpentWithChildren: 46.338203,
                  timeSpentWithFamily: 57.166805,
                  timeSpentWithPartner: 261.05215,
                  timeSpentWithCoworkers: 20.653986,
                },
                {
                  age: 73,
                  timeSpentAlone: 451.40637,
                  timeSpentWithFriends: 36.592476,
                  timeSpentWithChildren: 56.115063,
                  timeSpentWithFamily: 56.550076,
                  timeSpentWithPartner: 276.13379,
                  timeSpentWithCoworkers: 18.386124,
                },
                {
                  age: 74,
                  timeSpentAlone: 458.6745,
                  timeSpentWithFriends: 40.508751,
                  timeSpentWithChildren: 48.986588,
                  timeSpentWithFamily: 66.20977,
                  timeSpentWithPartner: 254.44495,
                  timeSpentWithCoworkers: 14.613341,
                },
                {
                  age: 75,
                  timeSpentAlone: 463.43195,
                  timeSpentWithFriends: 39.079994,
                  timeSpentWithChildren: 48.644051,
                  timeSpentWithFamily: 56.281876,
                  timeSpentWithPartner: 252.93309,
                  timeSpentWithCoworkers: 16.36656,
                },
                {
                  age: 76,
                  timeSpentAlone: 456.49493,
                  timeSpentWithFriends: 41.503906,
                  timeSpentWithChildren: 44.339306,
                  timeSpentWithFamily: 51.955276,
                  timeSpentWithPartner: 266.23712,
                  timeSpentWithCoworkers: 19.662245,
                },
                {
                  age: 77,
                  timeSpentAlone: 454.3125,
                  timeSpentWithFriends: 33.595589,
                  timeSpentWithChildren: 46.719131,
                  timeSpentWithFamily: 67.455605,
                  timeSpentWithPartner: 272.73013,
                  timeSpentWithCoworkers: 12.47935,
                },
                {
                  age: 78,
                  timeSpentAlone: 461.63959,
                  timeSpentWithFriends: 39.297825,
                  timeSpentWithChildren: 42.985035,
                  timeSpentWithFamily: 59.704296,
                  timeSpentWithPartner: 256.41376,
                  timeSpentWithCoworkers: 3.2494414,
                },
                {
                  age: 79,
                  timeSpentAlone: 485.83075,
                  timeSpentWithFriends: 41.975792,
                  timeSpentWithChildren: 38.609028,
                  timeSpentWithFamily: 51.944447,
                  timeSpentWithPartner: 235.3701,
                  timeSpentWithCoworkers: 2.0010538,
                },
                {
                  age: 80,
                  timeSpentAlone: 472.84854,
                  timeSpentWithFriends: 40.847649,
                  timeSpentWithChildren: 36.95074,
                  timeSpentWithFamily: 63.536056,
                  timeSpentWithPartner: 234.91951,
                  timeSpentWithCoworkers: 2.8974065,
                },
                {
                  age: 81,
                  timeSpentAlone: 466.04129,
                  timeSpentWithFriends: 43.080961,
                  timeSpentWithChildren: 32.866158,
                  timeSpentWithFamily: 62.430634,
                  timeSpentWithPartner: 237.56602,
                  timeSpentWithCoworkers: 3.1489592,
                },
                {
                  age: 82,
                  timeSpentAlone: 470.32001,
                  timeSpentWithFriends: 42.088737,
                  timeSpentWithChildren: 34.220249,
                  timeSpentWithFamily: 59.20015,
                  timeSpentWithPartner: 247.21811,
                  timeSpentWithCoworkers: 0.61405146,
                },
                {
                  age: 83,
                  timeSpentAlone: 475.89258,
                  timeSpentWithFriends: 45.554424,
                  timeSpentWithChildren: 32.232616,
                  timeSpentWithFamily: 59.157581,
                  timeSpentWithPartner: 229.67197,
                  timeSpentWithCoworkers: 0.53257704,
                },
                {
                  age: 84,
                  timeSpentAlone: 481.21349,
                  timeSpentWithFriends: 42.409515,
                  timeSpentWithChildren: 29.468161,
                  timeSpentWithFamily: 65.239105,
                  timeSpentWithPartner: 231.21817,
                  timeSpentWithCoworkers: 0.45110262,
                },
                {
                  age: 85,
                  timeSpentAlone: 489.2388,
                  timeSpentWithFriends: 44.268964,
                  timeSpentWithChildren: 27.172398,
                  timeSpentWithFamily: 68.797646,
                  timeSpentWithPartner: 226.32521,
                  timeSpentWithCoworkers: 0.53885528,
                },
              ],
            series: [
                {
                  type: "line",
                  xKey: "age",
                  xName: "Age",
                  yKey: "timeSpentAlone",
                  yName: "Alone",
                },
                {
                  type: "line",
                  xKey: "age",
                  xName: "Age",
                  yKey: "timeSpentWithFriends",
                  yName: "With Friends",
                },
                {
                  type: "line",
                  xKey: "age",
                  xName: "Age",
                  yKey: "timeSpentWithChildren",
                  yName: "With Children",
                },
                {
                  type: "line",
                  xKey: "age",
                  xName: "Age",
                  yKey: "timeSpentWithFamily",
                  yName: "With Family",
                },
                {
                  type: "line",
                  xKey: "age",
                  xName: "Age",
                  yKey: "timeSpentWithPartner",
                  yName: "With Partner",
                },
                {
                  type: "line",
                  xKey: "age",
                  xName: "Age",
                  yKey: "timeSpentWithCoworkers",
                  yName: "With Coworkers",
                },
              ],
            axes: [
                {
                  position: "bottom",
                  type: "number",
                  title: {
                    text: "Age",
                  },
                  nice: false,
                  min: 15,
                  max: 85,
                },
                {
                  position: "left",
                  type: "number",
                  title: {
                    text: "Time",
                  },
                  tick: {
                    values: [0, 180, 360, 540],
                  },
                  label: {
                    formatter: ({ value }) => `${Math.floor(value / 60)}h`,
                  },
                  crosshair: {
                    label: {
                      renderer: ({ value }) =>
                        `<div style="padding: 0 7px; border-radius: 2px; line-height: 1.7em; background-color: rgb(71,71,71); color: rgb(255, 255, 255);">${formatNumber(value)}</div>`,
                    },
                  },
                },
              ],
        },
        {
            id: 'line3',
            title: "Line With Time Axis",
            description: "When you have non-continuous graphs",
            footnote: "Source: Department of Environment, Food and Rural Affairs",
            data: [
                {
                  year: new Date(1990, 0, 1),
                  "Onshore wind": 1,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 11,
                  "Large scale Hydro": 437,
                  "Plant biomass": 0,
                  "Animal biomass": 0,
                  "Landfill gas": 46,
                  "Sewage gas": 104,
                },
                {
                  year: new Date(1991, 0, 1),
                  "Onshore wind": 1,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 12,
                  "Large scale Hydro": 385,
                  "Plant biomass": 0,
                  "Animal biomass": 0,
                  "Landfill gas": 68,
                  "Sewage gas": 108,
                },
                {
                  year: new Date(1992, 0, 1),
                  "Onshore wind": 3,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 13,
                  "Large scale Hydro": 454,
                  "Plant biomass": 0,
                  "Animal biomass": 17,
                  "Landfill gas": 124,
                  "Sewage gas": 108,
                },
                {
                  year: new Date(1993, 0, 1),
                  "Onshore wind": 19,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 14,
                  "Large scale Hydro": 356,
                  "Plant biomass": 0,
                  "Animal biomass": 52,
                  "Landfill gas": 147,
                  "Sewage gas": 124,
                },
                {
                  year: new Date(1994, 0, 1),
                  "Onshore wind": 30,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 14,
                  "Large scale Hydro": 424,
                  "Plant biomass": 0,
                  "Animal biomass": 71,
                  "Landfill gas": 170,
                  "Sewage gas": 118,
                },
                {
                  year: new Date(1995, 0, 1),
                  "Onshore wind": 34,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 14,
                  "Large scale Hydro": 402,
                  "Plant biomass": 0,
                  "Animal biomass": 71,
                  "Landfill gas": 184,
                  "Sewage gas": 135,
                },
                {
                  year: new Date(1996, 0, 1),
                  "Onshore wind": 42,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 10,
                  "Large scale Hydro": 282,
                  "Plant biomass": 0,
                  "Animal biomass": 67,
                  "Landfill gas": 232,
                  "Sewage gas": 135,
                },
                {
                  year: new Date(1997, 0, 1),
                  "Onshore wind": 57,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 14,
                  "Large scale Hydro": 344,
                  "Plant biomass": 0,
                  "Animal biomass": 68,
                  "Landfill gas": 301,
                  "Sewage gas": 134,
                },
                {
                  year: new Date(1998, 0, 1),
                  "Onshore wind": 75,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 18,
                  "Large scale Hydro": 422,
                  "Plant biomass": 0,
                  "Animal biomass": 76,
                  "Landfill gas": 389,
                  "Sewage gas": 126,
                },
                {
                  year: new Date(1999, 0, 1),
                  "Onshore wind": 73,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 18,
                  "Large scale Hydro": 441,
                  "Plant biomass": 0,
                  "Animal biomass": 157,
                  "Landfill gas": 558,
                  "Sewage gas": 135,
                },
                {
                  year: new Date(2000, 0, 1),
                  "Onshore wind": 81,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 18,
                  "Large scale Hydro": 419,
                  "Plant biomass": 11,
                  "Animal biomass": 183,
                  "Landfill gas": 718,
                  "Sewage gas": 120,
                },
                {
                  year: new Date(2001, 0, 1),
                  "Onshore wind": 83,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 18,
                  "Large scale Hydro": 331,
                  "Plant biomass": 81,
                  "Animal biomass": 205,
                  "Landfill gas": 822,
                  "Sewage gas": 119,
                },
                {
                  year: new Date(2002, 0, 1),
                  "Onshore wind": 108,
                  "Offshore wind": 0,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 18,
                  "Large scale Hydro": 394,
                  "Plant biomass": 92,
                  "Animal biomass": 184,
                  "Landfill gas": 879,
                  "Sewage gas": 121,
                },
                {
                  year: new Date(2003, 0, 1),
                  "Onshore wind": 110,
                  "Offshore wind": 1,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 13,
                  "Large scale Hydro": 257,
                  "Plant biomass": 137,
                  "Animal biomass": 169,
                  "Landfill gas": 1075,
                  "Sewage gas": 129,
                },
                {
                  year: new Date(2004, 0, 1),
                  "Onshore wind": 149,
                  "Offshore wind": 17,
                  "Marine energy": 0,
                  "Solar photovoltaics": 0,
                  "Small scale Hydro": 24,
                  "Large scale Hydro": 392,
                  "Plant biomass": 123,
                  "Animal biomass": 179,
                  "Landfill gas": 1313,
                  "Sewage gas": 144,
                },
                {
                  year: new Date(2005, 0, 1),
                  "Onshore wind": 215,
                  "Offshore wind": 35,
                  "Marine energy": 0,
                  "Solar photovoltaics": 1,
                  "Small scale Hydro": 38,
                  "Large scale Hydro": 385,
                  "Plant biomass": 129,
                  "Animal biomass": 159,
                  "Landfill gas": 1407,
                  "Sewage gas": 153,
                },
                {
                  year: new Date(2006, 0, 1),
                  "Onshore wind": 307,
                  "Offshore wind": 56,
                  "Marine energy": 0,
                  "Solar photovoltaics": 1,
                  "Small scale Hydro": 41,
                  "Large scale Hydro": 354,
                  "Plant biomass": 123,
                  "Animal biomass": 145,
                  "Landfill gas": 1451,
                  "Sewage gas": 146,
                },
                {
                  year: new Date(2007, 0, 1),
                  "Onshore wind": 386,
                  "Offshore wind": 67,
                  "Marine energy": 0,
                  "Solar photovoltaics": 1,
                  "Small scale Hydro": 45,
                  "Large scale Hydro": 392,
                  "Plant biomass": 138,
                  "Animal biomass": 218,
                  "Landfill gas": 1534,
                  "Sewage gas": 162,
                },
                {
                  year: new Date(2008, 0, 1),
                  "Onshore wind": 498,
                  "Offshore wind": 115,
                  "Marine energy": 0,
                  "Solar photovoltaics": 1,
                  "Small scale Hydro": 47,
                  "Large scale Hydro": 396,
                  "Plant biomass": 242,
                  "Animal biomass": 260,
                  "Landfill gas": 1540,
                  "Sewage gas": 180,
                },
                {
                  year: new Date(2009, 0, 1),
                  "Onshore wind": 647,
                  "Offshore wind": 151,
                  "Marine energy": 0,
                  "Solar photovoltaics": 2,
                  "Small scale Hydro": 49,
                  "Large scale Hydro": 401,
                  "Plant biomass": 387,
                  "Animal biomass": 232,
                  "Landfill gas": 1613,
                  "Sewage gas": 198,
                },
                {
                  year: new Date(2010, 0, 1),
                  "Onshore wind": 621,
                  "Offshore wind": 263,
                  "Marine energy": 0,
                  "Solar photovoltaics": 3,
                  "Small scale Hydro": 43,
                  "Large scale Hydro": 266,
                  "Plant biomass": 461,
                  "Animal biomass": 239,
                  "Landfill gas": 1711,
                  "Sewage gas": 237,
                },
                {
                  year: new Date(2011, 0, 1),
                  "Onshore wind": 930,
                  "Offshore wind": 443,
                  "Marine energy": 0,
                  "Solar photovoltaics": 21,
                  "Small scale Hydro": 61,
                  "Large scale Hydro": 429,
                  "Plant biomass": 554,
                  "Animal biomass": 224,
                  "Landfill gas": 1744,
                  "Sewage gas": 254,
                },
                {
                  year: new Date(2012, 0, 1),
                  "Onshore wind": 1053,
                  "Offshore wind": 654,
                  "Marine energy": 0,
                  "Solar photovoltaics": 116,
                  "Small scale Hydro": 58,
                  "Large scale Hydro": 398,
                  "Plant biomass": 1062,
                  "Animal biomass": 225,
                  "Landfill gas": 1708,
                  "Sewage gas": 242,
                },
                {
                  year: new Date(2013, 0, 1),
                  "Onshore wind": 1455,
                  "Offshore wind": 986,
                  "Marine energy": 0,
                  "Solar photovoltaics": 173,
                  "Small scale Hydro": 58,
                  "Large scale Hydro": 346,
                  "Plant biomass": 2008,
                  "Animal biomass": 226,
                  "Landfill gas": 1697,
                  "Sewage gas": 251,
                },
                {
                  year: new Date(2014, 0, 1),
                  "Onshore wind": 1595,
                  "Offshore wind": 1153,
                  "Marine energy": 0,
                  "Solar photovoltaics": 349,
                  "Small scale Hydro": 72,
                  "Large scale Hydro": 435,
                  "Plant biomass": 2913,
                  "Animal biomass": 225,
                  "Landfill gas": 1651,
                  "Sewage gas": 276,
                },
                {
                  year: new Date(2015, 0, 1),
                  "Onshore wind": 1965,
                  "Offshore wind": 1498,
                  "Marine energy": 0,
                  "Solar photovoltaics": 648,
                  "Small scale Hydro": 85,
                  "Large scale Hydro": 457,
                  "Plant biomass": 3850,
                  "Animal biomass": 235,
                  "Landfill gas": 1598,
                  "Sewage gas": 293,
                },
                {
                  year: new Date(2016, 0, 1),
                  "Onshore wind": 1785,
                  "Offshore wind": 1411,
                  "Marine energy": 0,
                  "Solar photovoltaics": 894,
                  "Small scale Hydro": 87,
                  "Large scale Hydro": 374,
                  "Plant biomass": 3855,
                  "Animal biomass": 230,
                  "Landfill gas": 1542,
                  "Sewage gas": 312,
                },
                {
                  year: new Date(2017, 0, 1),
                  "Onshore wind": 2470,
                  "Offshore wind": 1798,
                  "Marine energy": 0,
                  "Solar photovoltaics": 985,
                  "Small scale Hydro": 112,
                  "Large scale Hydro": 394,
                  "Plant biomass": 4206,
                  "Animal biomass": 226,
                  "Landfill gas": 1405,
                  "Sewage gas": 317,
                },
                {
                  year: new Date(2018, 0, 1),
                  "Onshore wind": 2612,
                  "Offshore wind": 2281,
                  "Marine energy": 1,
                  "Solar photovoltaics": 1089,
                  "Small scale Hydro": 111,
                  "Large scale Hydro": 357,
                  "Plant biomass": 4898,
                  "Animal biomass": 219,
                  "Landfill gas": 1284,
                  "Sewage gas": 325,
                },
                {
                  year: new Date(2019, 0, 1),
                  "Onshore wind": 2739,
                  "Offshore wind": 2749,
                  "Marine energy": 1,
                  "Solar photovoltaics": 1068,
                  "Small scale Hydro": 120,
                  "Large scale Hydro": 390,
                  "Plant biomass": 5400,
                  "Animal biomass": 243,
                  "Landfill gas": 866,
                  "Sewage gas": 233,
                },
                {
                  year: new Date(2020, 0, 1),
                  "Onshore wind": 3004,
                  "Offshore wind": 3498,
                  "Marine energy": 1,
                  "Solar photovoltaics": 1109,
                  "Small scale Hydro": 134,
                  "Large scale Hydro": 456,
                  "Plant biomass": 5637,
                  "Animal biomass": 241,
                  "Landfill gas": 835,
                  "Sewage gas": 237,
                },
                {
                  year: new Date(2021, 0, 1),
                  "Onshore wind": 2507,
                  "Offshore wind": 3053,
                  "Marine energy": 0,
                  "Solar photovoltaics": 1044,
                  "Small scale Hydro": 119,
                  "Large scale Hydro": 353,
                  "Plant biomass": 5990,
                  "Animal biomass": 240,
                  "Landfill gas": 791,
                  "Sewage gas": 233,
                },
              ],
            series: [
                {
                  type: "line",
                  xKey: "year",
                  yKey: "Onshore wind",
                  yName: "Onshore Wind",
                },
                {
                  type: "line",
                  xKey: "year",
                  yKey: "Offshore wind",
                  yName: "Offshore Wind",
                },
                {
                  type: "line",
                  xKey: "year",
                  yKey: "Solar photovoltaics",
                  yName: "Solar Photovoltaics",
                },
                {
                  type: "line",
                  xKey: "year",
                  yKey: "Plant biomass",
                  yName: "Plant Biomass",
                },
                {
                  type: "line",
                  xKey: "year",
                  yKey: "Landfill gas",
                  yName: "Landfill Gas",
                },
              ],
            axes: [
                {
                  position: "bottom",
                  type: "time",
                  min: new Date(2000, 0, 1),
                  max: new Date(2022, 0, 1),
                  nice: false,
                  crosshair: {
                    label: {
                      format: `%b %Y`,
                    },
                  },
                  crossLines: [
                    {
                      type: "line",
                      value: new Date(2020, 0, 1),
                      label: {
                        text: "COVID-19 START",
                        padding: 10,
                      },
                    },
                  ],
                },
                {
                  position: "right",
                  type: "number",
                  title: {
                    text: `ktoe`,
                  },
                  label: {
                    formatter: (params) => `${params.value / 1000}K`,
                  },
                },
              ],
            theme: {
                overrides: {
                  line: {
                    series: {
                      lineDash: [12, 3],
                      marker: {
                        enabled: false,
                      },
                      tooltip: {
                        renderer: ({ datum, xKey, yKey }) => {
                          const date = Intl.DateTimeFormat("en-GB", {
                            year: "numeric",
                            month: "short",
                          }).format(datum[xKey]);
                          return { content: `${date}: ${datum[yKey].toFixed(0)}` };
                        },
                      },
                    },
                  },
                },
              }
        },
        {
            id: 'line4',
            title: "Large data sets",
            description: "Trigonometric Functions",
            footnote: "From -2π to 2π, one cycle within 2π",
            data: bigData,
            series: [
                {
                  type: "line",
                  xKey: "x",
                  yKey: "sinX",
                  yName: "Sine",
                  strokeWidth: 4,
                  marker: {
                    enabled: false,
                  },
                },
                {
                  type: "line",
                  xKey: "x",
                  yKey: "cosX",
                  yName: "Cosine",
                  strokeWidth: 4,
                  marker: {
                    enabled: false,
                  },
                },
                {
                  type: "line",
                  xKey: "x",
                  yKey: "tanX",
                  yName: "Tangent",
                  strokeWidth: 4,
                  marker: {
                    enabled: false,
                  },
                },
                {
                  type: "line",
                  xKey: "x",
                  yKey: "cscX",
                  yName: "Cosecant",
                  lineDash: [4, 1, 4],
                  strokeWidth: 3,
                  marker: {
                    enabled: false,
                  },
                },
                {
                  type: "line",
                  xKey: "x",
                  yKey: "secX",
                  yName: "Secant",
                  lineDash: [4, 1, 4],
                  strokeWidth: 3,
                  marker: {
                    enabled: false,
                  },
                },
                {
                  type: "line",
                  xKey: "x",
                  yKey: "cotX",
                  yName: "Cotangent",
                  lineDash: [4, 1, 4],
                  strokeWidth: 3,
                  marker: {
                    enabled: false,
                  },
                },
              ],
            axes: [
                {
                  position: "left",
                  type: "number",
                  min: -3,
                  max: 3,
                  crossLines: [
                    {
                      type: "line",
                      value: 0,
                      label: {
                        text: "► X",
                        fontSize: 15,
                        position: "right",
                        padding: 0,
                      },
                    },
                    {
                      type: "range",
                      range: [-1, 1],
                      strokeWidth: 0,
                    },
                  ],
                },
            ]
        },
    ]

    return demoCharts;
}
