export const definitions = {
    "pinned_tweet_id": "Unique identifier of this user's pinned Tweet.",
    "public_metrics": "Public engagement metrics for the Tweet at the time of the request. This will pull retweet_count, reply_count, like_count and quote_count",
    "attachments": "Specifies the type of attachments (if any) present in this Tweet.",
    "author_id": "The unique identifier of the User who posted this Tweet.",
    "conversation_id": "The Tweet ID of the original Tweet of the conversation (which includes direct replies, replies of replies).",
    "created_at": "Creation time of the Tweet. in ISO 8601 format (conversion to standart datetime coming soon)",
    "edit_controls": "When present, this indicates how much longer the Tweet can be edited and the number of remaining edits. Tweets are only editable for the first 30 minutes after creation and can be edited up to five times.",
    "entities": "Entities that have been parsed out of the text of the Tweet. Additionally, see entities in Twitter Objects.",
    "in_reply_to_user_id": "If the represented Tweet is a reply, this field will contain the original Tweet’s author ID. This will not necessarily always be the user directly mentioned in the Tweet.",
    "lang": "Language of the Tweet, if detected by Twitter. Returned as a BCP47 language tag.",
    "referenced_tweets": "A list of Tweets this Tweet refers to. For example, if the parent Tweet is a Retweet, a Retweet with comment (also known as Quoted Tweet) or a Reply, it will include the related Tweet referenced to by its parent.",
    "User Deatils: created_at": "The UTC datetime that the user account was created on Twitter.",
    "User Details: description": "The text of this user's profile description (also known as bio), if the user provided one.",
    "User Details: entities": "Contains details about text that has a special meaning in the user's description.",
    "User Details: id ": "The unique identifier of this user.",
    "User Details: location": "The location specified in the user's profile, if the user provided one. As this is a freeform value, it may not indicate a valid location, but it may be fuzzily evaluated when performing searches with location queries.",
    "User Details: profile_image_url": "The URL to the profile image for this user, as shown on the user's profile.",
    "User Details: protected": "Indicates if this user has chosen to protect their Tweets (in other words, if this user's Tweets are private).",
    "User Details: public_metrics": "Contains details about activity for this user. Gathers followers_count, following_count, tweet_count and listed_count",
    "User Details: url": "The URL specified in the user's profile, if present.",
    "User Details: verified": "Indicates if this user is a verified Twitter User.",
    "List Details: id ": "The unique identifier of this List.",
    "List Details: name ": "The name of the List, as defined when creating the List",
    "List Details: created_at": "The UTC datetime that the List was created on Twitter.",
    "List Details: description": "A brief description to let users know about the List.",
    "List Details: follower_count": "Shows how many users follow this List,",
    "List Details: private": "Indicates if the List is private.",
    "List Details: owner_id": "Unique identifier of this List's owner.",
}