import { KALSHI_GUIDED_TARGETS } from "../targets";
import type { GuidedStep, GuidedWorkflowDefinition } from "../types";

const CATEGORY_COLUMN = "kalshi_taxonomy_category";

function columnSelectStep(
  column: string,
  title: string,
  body: string,
  placement: GuidedStep["placement"] = "bottom",
): GuidedStep {
  return {
    id: `select-column-${column}`,
    target: KALSHI_GUIDED_TARGETS.column(column),
    title,
    body,
    placement,
    completeWhen: {
      type: "state",
      match: { selectedColumns: { includes: [column] } },
    },
    waitForTarget: true,
  };
}

export const top10WeatherMarketsSince2021Workflow: GuidedWorkflowDefinition = {
  id: "top-10-weather-markets-since-2021",
  title: "Get top 10 weather markets, all time by volume",
  description: "Find and rank the highest-volume weather markets since Kalshi launched in 2021",
  steps: [
    {
      id: "select-markets-source",
      target: KALSHI_GUIDED_TARGETS.sourceMarkets,
      title: "Select the Markets data source",
      body: "This is a Markets data pull, so we will first select the Markets data source.",
      placement: "right",
      completeWhen: { type: "click" },
      assert: { sampleId: "athena-kal-markets" },
      waitForTarget: true,
    },
    {
      id: "columns-fields-overview",
      kind: "info",
      target: KALSHI_GUIDED_TARGETS.columnsPanel,
      title: "Market fields",
      body: "These are all the fields you can include for each market in your pull. In the next steps, we'll show you exactly which ones to select.",
      placement: "bottom",
      completeWhen: { type: "continue" },
      waitForTarget: true,
      blockTargetInteraction: true,
    },
    columnSelectStep(
      "ticker",
      "Select ticker",
      "The unique market identifier set by Kalshi.",
    ),
    columnSelectStep(
      "kalshi_taxonomy_category",
      "Select Category",
      "The meta market category. Kalshi does not natively classify markets by category, but Lychee's AI has extrapolated this to make your life easier. Categories can be Sports, Weather, Politics, Crypto, and more.",
    ),
    columnSelectStep(
      "title",
      "Select title",
      "The human-readable title. This is useful to know exactly which market you are looking at.",
    ),
    columnSelectStep(
      "yes_sub_title",
      "Select yes_sub_title",
      "The proposed Yes outcome for this specific market.",
    ),
    columnSelectStep(
      "status",
      "Select status",
      "Whether the market is still open, has been closed, or has been finalized. A closed market has stopped accepting new trades because its event has concluded, but still awaits official confirmation. A finalized (settled) market is one where Kalshi has received official data from the pre-established source agency and distributed payouts to winning positions.",
      "top",
    ),
    columnSelectStep(
      "last_price",
      "Select last_price",
      "The last traded price before market close — a useful data point to include in a top-10 markets pull.",
    ),
    columnSelectStep(
      "volume",
      "Select volume",
      "Total contracts traded over the market's lifespan. You will need this field for the sort in this workflow.",
    ),
    columnSelectStep(
      "created_time",
      "Select created_time",
      "When the market was created.",
    ),
    columnSelectStep(
      "open_time",
      "Select open_time",
      "When trading on the market began.",
    ),
    columnSelectStep(
      "close_time",
      "Select close_time",
      "When trading for this market closed.",
    ),
    {
      id: "filters-overview",
      kind: "info",
      target: KALSHI_GUIDED_TARGETS.composePanel,
      title: "Filters",
      body: "These are filters. You can also run filters and operations after your data is pulled, directly in the Lychee data sheet. However, we recommend applying preliminary filters here to reduce query load — smaller queries execute faster and consume less memory.",
      placement: "top",
      completeWhen: { type: "continue" },
      waitForTarget: true,
      blockTargetInteraction: true,
    },
    {
      id: "open-where-op",
      target: KALSHI_GUIDED_TARGETS.composeOp("where"),
      title: "Select Where",
      body: "Where lets you filter rows using a conditional expression.",
      placement: "bottom",
      completeWhen: { type: "click" },
      assert: { activeComposeOps: { includes: "where" } },
      waitForTarget: true,
    },
    {
      id: "where-add-filter",
      target: KALSHI_GUIDED_TARGETS.whereAdd,
      title: 'Select "Select column you want to filter"',
      body: "We will first define the column property by which we want to filter the dataset. You can add multiple Where filters, but we only need one for this workflow.",
      placement: "top",
      completeWhen: { type: "click" },
      waitForTarget: true,
    },
    {
      id: "where-pick-category",
      target: KALSHI_GUIDED_TARGETS.whereAdd,
      title: "Select Category",
      body: "Open the menu and choose Category from the list.",
      placement: "top",
      completeWhen: {
        type: "state",
        match: { whereFilter: { column: CATEGORY_COLUMN } },
      },
      waitForTarget: true,
    },
    {
      id: "where-operator-explainer",
      kind: "info",
      target: KALSHI_GUIDED_TARGETS.whereOp,
      title: "Filter operator (=)",
      body: 'The "=" operator means direct equivalence. Other options include "is equal to", "not equal to", and "in set" — where you can specify a list of values the filter may match.',
      placement: "left",
      completeWhen: { type: "continue" },
      waitForTarget: true,
      blockTargetInteraction: true,
    },
    {
      id: "where-enter-weather",
      target: KALSHI_GUIDED_TARGETS.whereValue,
      title: "Enter Weather",
      body: "Type Weather in the value field to filter to weather markets only. This match is not case-sensitive.",
      placement: "top",
      completeWhen: {
        type: "state",
        match: {
          whereFilter: { column: CATEGORY_COLUMN, valueEqualsIgnoreCase: "Weather" },
        },
      },
      waitForTarget: true,
    },
    {
      id: "open-sort-op",
      target: KALSHI_GUIDED_TARGETS.composeOp("sort"),
      title: "Select Sort",
      body: "Sort controls the order rows are returned in your pull.",
      placement: "bottom",
      completeWhen: { type: "click" },
      assert: { activeComposeOps: { includes: "sort" } },
      waitForTarget: true,
    },
    {
      id: "sort-add-clause",
      target: KALSHI_GUIDED_TARGETS.sortAdd,
      title: "Add sort",
      body: "Add a sort rule so we can rank markets by volume.",
      placement: "bottom",
      completeWhen: { type: "click" },
      waitForTarget: true,
    },
    {
      id: "sort-by-volume",
      target: KALSHI_GUIDED_TARGETS.sortColumn,
      title: 'Sort by "volume"',
      body: "Choose volume as the sort column so highest-volume markets appear first.",
      placement: "bottom",
      completeWhen: {
        type: "state",
        match: { orderBy: { alias: "volume" } },
      },
      waitForTarget: true,
    },
    {
      id: "sort-desc-volume",
      target: KALSHI_GUIDED_TARGETS.sortDirection,
      title: "Descending order",
      body: "Descending returns markets from greatest volume to lowest. Without a row limit, this still pulls every weather market sorted by volume — we will add a limit next.",
      placement: "bottom",
      completeWhen: {
        type: "state",
        match: { orderBy: { alias: "volume", direction: "desc" } },
      },
      waitForTarget: true,
    },
    {
      id: "open-limit-op",
      target: KALSHI_GUIDED_TARGETS.composeOp("row_limit"),
      title: "Select Limit",
      body: "Limit caps how many rows are returned so the pull stays fast and focused.",
      placement: "bottom",
      completeWhen: { type: "click" },
      assert: { activeComposeOps: { includes: "row_limit" } },
      waitForTarget: true,
    },
    {
      id: "limit-set-rows",
      target: KALSHI_GUIDED_TARGETS.limitSet,
      title: "Set row limit",
      body: "Open the row limit controls so we can cap this pull.",
      placement: "bottom",
      completeWhen: { type: "click" },
      waitForTarget: true,
    },
    {
      id: "limit-max-ten",
      target: KALSHI_GUIDED_TARGETS.limitValue,
      title: 'Set maximum rows to 10',
      body: "Enter 10 as the maximum rows. This pulls only the top 10 weather markets by volume in descending order.",
      placement: "top",
      completeWhen: {
        type: "state",
        match: { composeLimitOpen: true, composeLimitValue: "10" },
      },
      waitForTarget: true,
    },
    {
      id: "name-sheet",
      target: KALSHI_GUIDED_TARGETS.sheetName,
      title: "Name your sheet",
      body: "Give this pull a sheet name — you can rename it later, but labeling your data now is good practice for organization.",
      placement: "top",
      completeWhen: {
        type: "state",
        match: { sheetNameNonEmpty: true },
      },
      waitForTarget: true,
    },
    {
      id: "run-query",
      target: KALSHI_GUIDED_TARGETS.runQuery,
      title: "Run for Free",
      body: "When everything looks right, run the query to pull your top 10 weather markets into Lychee.",
      placement: "top",
      completeWhen: { type: "click" },
      waitForTarget: true,
    },
  ],
};
